import type { Locale } from './locale'

export type LocaleCopy = {
  siteName: string
  menu: string
  nav: { docs: string; quickstart: string; api: string; models: string; community: string; getStarted: string }
  home: {
    eyebrow: string
    title: string
    description: string
    quickstart: string
    getKey: string
    apiReference: string
    cards: Array<{ title: string; body: string }>
    codeLabel: string
    links: { overview: string; billing: string; models: string; fiveMinutes: string }
  }
  quickstart: {
    title: string
    description: string
    headings: { key: string; endpoints: string; curl: string; sdk: string; next: string }
    keyBody: string
    endpointBody: string
    endpointStandard: string
    endpointMedia: string
    curlBody: string
    sdkBody: string
    nextBody: string
    nextLinks: { api: string; models: string; billing: string }
  }
  core: {
    overview: { title: string; description: string; heading: string; body: string; bullets: string[] }
    auth: { title: string; description: string; heading: string; body: string; bullets: string[] }
    faq: { title: string; description: string; heading: string; body: string; bullets: string[] }
  }
}

const EN: LocaleCopy = {
  siteName: 'gpt88.cc API Docs',
  menu: 'Language',
  nav: { docs: 'Docs', quickstart: 'Quickstart', api: 'API Reference', models: 'Models', community: 'Community', getStarted: 'Get Started' },
  home: {
    eyebrow: 'Unified API Gateway · OpenAI Compatible',
    title: 'One base_url for all models on gpt88.cc',
    description: 'Use GPT, Claude, Gemini, DeepSeek, Qwen, image models, and more through one OpenAI-compatible API. Replace the Base URL and API key, then keep your existing SDK.',
    quickstart: 'Quickstart', getKey: 'Get API Key', apiReference: 'API Reference',
    cards: [
      { title: 'Minimal migration', body: 'Replace the Base URL and API key. Keep the same OpenAI-style request body.' },
      { title: 'One gateway, many models', body: 'Switch between chat, image, video, and audio models with a consistent integration path.' },
      { title: 'Usage-based billing', body: 'See actual usage and account balance clearly. No opaque virtual-points conversion.' },
    ],
    codeLabel: 'Quick cURL',
    links: { overview: 'Overview', billing: 'Auth & Billing', models: 'Models', fiveMinutes: 'Start in 5 minutes' },
  },
  quickstart: {
    title: 'Quickstart', description: 'Make your first gpt88.cc API request in 5 minutes by replacing only the Base URL and API key.',
    headings: { key: 'Get an API key', endpoints: 'Endpoints', curl: 'cURL request', sdk: 'Official SDK', next: 'Next steps' },
    keyBody: 'Create an API key in the console and export it into your shell environment.',
    endpointBody: 'Use the standard API route for text and multimodal requests. Use the media route for direct image and video tasks.',
    endpointStandard: 'Standard OpenAI, Claude, Gemini, and audio APIs.', endpointMedia: 'Direct image and video APIs.',
    curlBody: 'Send a minimal chat request to verify the key, route, and model ID.',
    sdkBody: 'Any OpenAI-compatible SDK can be used by pointing base_url to the standard API route.',
    nextBody: 'Continue with the API reference, model catalog, or billing guide.',
    nextLinks: { api: 'Read the Chat Completions API reference', models: 'Browse available models', billing: 'Review auth and billing behavior' },
  },
  core: {
    overview: { title: 'Overview', description: 'A practical overview of the gpt88.cc unified AI API gateway.', heading: 'One integration path for many AI models', body: 'gpt88.cc provides a unified OpenAI-compatible entry point for developers who need to compare models, change providers, or move an existing application between routes.', bullets: ['Use one Base URL and API key pattern.', 'Compare model capability, latency, and cost from the model catalog.', 'Choose a standard, overseas direct, or overseas CDN route when needed.'] },
    auth: { title: 'Auth & Billing', description: 'Authentication, API key safety, usage-based billing, and quota guidance.', heading: 'Keep credentials server-side and track actual usage', body: 'Use Bearer authentication for every request. Store keys in environment variables or a secret manager, and check the live console for current models, pricing, quota, and route availability.', bullets: ['Never expose an API key in browser code or a public repository.', 'Rotate a leaked key immediately from the console.', 'Use the current console record as the source of truth for billing and quota.'] },
    faq: { title: 'FAQ', description: 'Common questions about compatibility, routes, billing, security, and troubleshooting.', heading: 'Answers before your first production request', body: 'The API is designed for OpenAI-compatible clients and SDKs. Start with the standard route, verify the model ID with GET /v1/models, and keep the request ID when troubleshooting.', bullets: ['Existing OpenAI SDKs can usually work by changing Base URL and API key.', 'Model availability, pricing, and quotas are account-specific.', 'Use exponential backoff for rate limits and temporary upstream failures.'] },
  },
}

const TRANSLATIONS: Partial<Record<Locale, Partial<LocaleCopy>>> = {
  zh: {
    siteName: 'GPT88 API 文档', menu: '语言',
    nav: { docs: '文档', quickstart: '快速开始', api: 'API 参考', models: '模型导航', community: '社区', getStarted: '开始使用' },
    home: {
      eyebrow: '统一 API 网关 · OpenAI 兼容',
      title: '一个 API，接入所有主流模型',
      description: '通过一套 OpenAI 兼容 API 使用 GPT、Claude、Gemini、DeepSeek、Qwen、图片模型等能力。只需替换 Base URL 和 API Key，即可继续使用现有 SDK。',
      quickstart: '快速开始', getKey: '获取 API Key', apiReference: 'API 参考',
      cards: [
        { title: '最小化迁移', body: '替换 Base URL 和 API Key，保留原有的 OpenAI 请求结构。' },
        { title: '一个网关，多种模型', body: '使用一致的接入方式切换聊天、图片、视频和音频模型。' },
        { title: '按用量计费', body: '清楚查看实际用量与账户余额，不使用不透明的虚拟积分换算。' },
      ],
      codeLabel: '快速 cURL',
      links: { overview: '产品概览', billing: '认证与计费', models: '模型', fiveMinutes: '五分钟开始' },
    },
    quickstart: {
      title: '快速开始', description: '只需替换 Base URL 和 API Key，五分钟完成第一次 gpt88.cc API 调用。',
      headings: { key: '获取 API Key', endpoints: 'API 端点', curl: 'cURL 请求', sdk: '官方 SDK', next: '下一步' },
      keyBody: '在控制台创建 API Key，并导出到终端环境变量。',
      endpointBody: '文本和多模态请求使用标准 API 路由；图片和视频任务使用媒体路由。',
      endpointStandard: '标准 OpenAI、Claude、Gemini 和音频 API。', endpointMedia: '图片和视频 API。',
      curlBody: '发送最小聊天请求，验证 Key、路由和模型 ID。',
      sdkBody: '任何 OpenAI 兼容 SDK 都可以将 base_url 指向标准 API 路由。',
      nextBody: '继续阅读 API 参考、模型目录或计费指南。',
      nextLinks: { api: '阅读 Chat Completions API 参考', models: '浏览可用模型', billing: '查看认证与计费' },
    },
  },
  'zh-TW': {
    siteName: 'gpt88.cc API 文件', menu: '語言',
    nav: { docs: '文件', quickstart: '快速開始', api: 'API 參考', models: '模型', community: '社群', getStarted: '開始使用' },
    home: { eyebrow: '統一 API 閘道 · OpenAI 相容', title: '一個 base_url 接入 gpt88.cc 的所有模型', description: '透過一個 OpenAI 相容 API 使用 GPT、Claude、Gemini、DeepSeek、Qwen 及圖片模型。只需替換 Base URL 和 API Key，即可保留現有 SDK。', quickstart: '快速開始', getKey: '取得 API Key', apiReference: 'API 參考', cards: [{ title: '最小化遷移', body: '替換 Base URL 和 API Key，保留原有的 OpenAI 請求格式。' }, { title: '一個閘道，多種模型', body: '以一致的接入方式切換聊天、圖片、影片和音訊模型。' }, { title: '按用量計費', body: '清楚查看實際用量與帳戶餘額，不使用不透明的虛擬積分換算。' }], codeLabel: '快速 cURL', links: { overview: '產品概覽', billing: '認證與計費', models: '模型', fiveMinutes: '五分鐘開始' } },
    quickstart: { title: '快速開始', description: '只需替換 Base URL 和 API Key，五分鐘完成第一次 gpt88.cc API 呼叫。', headings: { key: '取得 API Key', endpoints: 'API 端點', curl: 'cURL 請求', sdk: '官方 SDK', next: '下一步' }, keyBody: '在控制台建立 API Key，並匯出到終端機環境變數。', endpointBody: '文字和多模態請求使用標準 API 路線；圖片和影片任務使用媒體路線。', endpointStandard: '標準 OpenAI、Claude、Gemini 和音訊 API。', endpointMedia: '圖片和影片 API。', curlBody: '發送最小聊天請求，驗證 Key、路線和模型 ID。', sdkBody: '任何 OpenAI 相容 SDK 都可以將 base_url 指向標準 API 路線。', nextBody: '繼續閱讀 API 參考、模型目錄或計費指南。', nextLinks: { api: '閱讀 Chat Completions API 參考', models: '瀏覽可用模型', billing: '查看認證與計費' } },
    core: { overview: { title: '產品概覽', description: 'gpt88.cc 統一 AI API 閘道概覽。', heading: '一套接入方式使用多種 AI 模型', body: 'gpt88.cc 為需要比較模型、切換供應商或調整線路的開發者提供統一的 OpenAI 相容入口。', bullets: ['使用一致的 Base URL 和 API Key 格式。', '在模型目錄中比較能力、延遲和成本。', '按需選擇標準、海外直連或海外 CDN 路線。'] }, auth: { title: '認證與計費', description: '認證、API Key 安全、按用量計費和配額說明。', heading: '在服務端保管憑證並追蹤實際用量', body: '每次請求使用 Bearer 認證。請將 Key 儲存在環境變數或密鑰管理器中，並以控制台的即時資訊為準。', bullets: ['不要在瀏覽器程式碼或公開倉庫暴露 API Key。', '發現洩漏後立即在控制台撤銷並輪換。', '價格、配額、模型和路線以目前控制台為準。'] }, faq: { title: '常見問題', description: '相容性、路線、計費、安全和排障常見問題。', heading: '第一次正式請求前先查看這裡', body: 'API 面向 OpenAI 相容客戶端和 SDK。先使用標準路線，再用 GET /v1/models 驗證模型 ID。', bullets: ['大多數 OpenAI SDK 只需修改 Base URL 和 API Key。', '模型、價格和配額取決於帳戶設定。', '遇到限速或暫時性故障時使用指數退避重試。'] } },
  },
  es: {
    siteName: 'Documentación API de gpt88.cc', menu: 'Idioma',
    nav: { docs: 'Documentación', quickstart: 'Inicio rápido', api: 'Referencia API', models: 'Modelos', community: 'Comunidad', getStarted: 'Comenzar' },
    home: { eyebrow: 'Pasarela API unificada · Compatible con OpenAI', title: 'Un base_url para todos los modelos de gpt88.cc', description: 'Usa GPT, Claude, Gemini, DeepSeek, Qwen y modelos de imagen mediante una API compatible con OpenAI. Cambia el Base URL y la API Key sin reescribir tu SDK.', quickstart: 'Inicio rápido', getKey: 'Obtener API Key', apiReference: 'Referencia API', cards: [{ title: 'Migración mínima', body: 'Cambia el Base URL y la API Key, y conserva el cuerpo de solicitud de OpenAI.' }, { title: 'Una pasarela, muchos modelos', body: 'Cambia entre modelos de chat, imagen, vídeo y audio con una integración uniforme.' }, { title: 'Facturación por uso', body: 'Consulta el uso real y el saldo de forma clara, sin conversiones opacas de puntos.' }], codeLabel: 'cURL rápido', links: { overview: 'Descripción general', billing: 'Auth y facturación', models: 'Modelos', fiveMinutes: 'Empieza en 5 minutos' } },
    quickstart: { title: 'Inicio rápido', description: 'Realiza tu primera solicitud a la API de gpt88.cc en 5 minutos cambiando solo el Base URL y la API Key.', headings: { key: 'Obtén una API Key', endpoints: 'Endpoints', curl: 'Solicitud cURL', sdk: 'SDK oficial', next: 'Siguientes pasos' }, keyBody: 'Crea una API Key en la consola y expórtala en el entorno de tu terminal.', endpointBody: 'Usa la ruta estándar para texto y multimodal. Usa la ruta multimedia para tareas directas de imagen y vídeo.', endpointStandard: 'APIs estándar de OpenAI, Claude, Gemini y audio.', endpointMedia: 'APIs directas de imagen y vídeo.', curlBody: 'Envía una solicitud de chat mínima para verificar la clave, la ruta y el modelo.', sdkBody: 'Cualquier SDK compatible con OpenAI puede apuntar su base_url a la ruta estándar.', nextBody: 'Continúa con la referencia API, el catálogo de modelos o la guía de facturación.', nextLinks: { api: 'Leer la referencia Chat Completions', models: 'Explorar modelos disponibles', billing: 'Ver autenticación y facturación' } },
    core: { overview: { title: 'Descripción general', description: 'Descripción de la pasarela de IA unificada de gpt88.cc.', heading: 'Una integración para muchos modelos de IA', body: 'gpt88.cc ofrece una entrada compatible con OpenAI para comparar modelos, cambiar de proveedor y mover aplicaciones entre rutas.', bullets: ['Usa un patrón común de Base URL y API Key.', 'Compara capacidades, latencia y coste en el catálogo.', 'Elige una ruta estándar, directa internacional o CDN internacional.'] }, auth: { title: 'Auth y facturación', description: 'Autenticación, seguridad de API Key, facturación por uso y cuotas.', heading: 'Protege las credenciales y controla el uso real', body: 'Usa Bearer en cada solicitud. Guarda las claves en variables de entorno o un gestor de secretos y consulta la consola para los valores actuales.', bullets: ['Nunca expongas la API Key en el navegador o en un repositorio público.', 'Revoca inmediatamente una clave comprometida.', 'La consola es la fuente actual para precios, modelos, cuotas y rutas.'] }, faq: { title: 'Preguntas frecuentes', description: 'Preguntas sobre compatibilidad, rutas, facturación, seguridad y errores.', heading: 'Respuestas antes de tu primera solicitud de producción', body: 'La API está pensada para clientes y SDK compatibles con OpenAI. Empieza con la ruta estándar y verifica el modelo con GET /v1/models.', bullets: ['Normalmente solo necesitas cambiar Base URL y API Key.', 'Los modelos, precios y límites dependen de la cuenta.', 'Usa backoff exponencial para límites y fallos temporales.'] } },
  },
  'pt-BR': {
    siteName: 'Documentação da API gpt88.cc', menu: 'Idioma',
    nav: { docs: 'Documentação', quickstart: 'Início rápido', api: 'Referência da API', models: 'Modelos', community: 'Comunidade', getStarted: 'Começar' },
    home: { eyebrow: 'Gateway de API unificado · Compatível com OpenAI', title: 'Um base_url para todos os modelos da gpt88.cc', description: 'Use GPT, Claude, Gemini, DeepSeek, Qwen e modelos de imagem por uma API compatível com OpenAI. Troque o Base URL e a API Key sem reescrever seu SDK.', quickstart: 'Início rápido', getKey: 'Obter API Key', apiReference: 'Referência da API', cards: [{ title: 'Migração mínima', body: 'Troque o Base URL e a API Key e mantenha o corpo de requisição no padrão OpenAI.' }, { title: 'Um gateway, muitos modelos', body: 'Alterne entre modelos de chat, imagem, vídeo e áudio com uma integração consistente.' }, { title: 'Cobrança por uso', body: 'Veja o uso real e o saldo com clareza, sem conversão opaca de pontos virtuais.' }], codeLabel: 'cURL rápido', links: { overview: 'Visão geral', billing: 'Autenticação e cobrança', models: 'Modelos', fiveMinutes: 'Comece em 5 minutos' } },
    quickstart: { title: 'Início rápido', description: 'Faça sua primeira chamada à API gpt88.cc em 5 minutos trocando apenas o Base URL e a API Key.', headings: { key: 'Obter uma API Key', endpoints: 'Endpoints', curl: 'Requisição cURL', sdk: 'SDK oficial', next: 'Próximos passos' }, keyBody: 'Crie uma API Key no console e exporte-a para o ambiente do terminal.', endpointBody: 'Use a rota padrão para texto e multimodal. Use a rota de mídia para tarefas diretas de imagem e vídeo.', endpointStandard: 'APIs padrão de OpenAI, Claude, Gemini e áudio.', endpointMedia: 'APIs diretas de imagem e vídeo.', curlBody: 'Envie uma chamada de chat mínima para validar a chave, a rota e o modelo.', sdkBody: 'Qualquer SDK compatível com OpenAI pode apontar seu base_url para a rota padrão.', nextBody: 'Continue pela referência da API, catálogo de modelos ou guia de cobrança.', nextLinks: { api: 'Ler a referência Chat Completions', models: 'Ver modelos disponíveis', billing: 'Revisar autenticação e cobrança' } },
    core: { overview: { title: 'Visão geral', description: 'Visão geral do gateway unificado de IA da gpt88.cc.', heading: 'Uma integração para muitos modelos de IA', body: 'A gpt88.cc oferece uma entrada compatível com OpenAI para comparar modelos, trocar provedores e mover aplicações entre rotas.', bullets: ['Use um padrão único de Base URL e API Key.', 'Compare capacidade, latência e custo no catálogo.', 'Escolha rota padrão, direta internacional ou CDN internacional.'] }, auth: { title: 'Autenticação e cobrança', description: 'Autenticação, segurança de API Key, cobrança por uso e cotas.', heading: 'Proteja as credenciais e acompanhe o uso real', body: 'Use Bearer em cada requisição. Guarde as chaves em variáveis de ambiente ou um gerenciador de segredos e consulte o console para os valores atuais.', bullets: ['Nunca exponha a API Key no navegador ou em repositório público.', 'Revogue imediatamente uma chave comprometida.', 'Preços, modelos, cotas e rotas devem ser confirmados no console.'] }, faq: { title: 'Perguntas frequentes', description: 'Perguntas sobre compatibilidade, rotas, cobrança, segurança e erros.', heading: 'Respostas antes da primeira chamada de produção', body: 'A API foi projetada para clientes e SDKs compatíveis com OpenAI. Comece pela rota padrão e valide o modelo com GET /v1/models.', bullets: ['Normalmente basta trocar Base URL e API Key.', 'Modelos, preços e limites dependem da conta.', 'Use backoff exponencial para limites e falhas temporárias.'] } },
  },
  fr: {
    siteName: 'Documentation API gpt88.cc', menu: 'Langue',
    nav: { docs: 'Documentation', quickstart: 'Démarrage rapide', api: 'Référence API', models: 'Modèles', community: 'Communauté', getStarted: 'Commencer' },
    home: { eyebrow: 'Passerelle API unifiée · Compatible OpenAI', title: 'Un seul base_url pour tous les modèles gpt88.cc', description: 'Utilisez GPT, Claude, Gemini, DeepSeek, Qwen et les modèles d’image avec une API compatible OpenAI. Remplacez le Base URL et la clé sans réécrire votre SDK.', quickstart: 'Démarrage rapide', getKey: 'Obtenir une clé API', apiReference: 'Référence API', cards: [{ title: 'Migration minimale', body: 'Remplacez le Base URL et la clé API, en conservant le corps de requête OpenAI.' }, { title: 'Une passerelle, plusieurs modèles', body: 'Passez du chat à l’image, la vidéo et l’audio avec une intégration cohérente.' }, { title: 'Facturation à l’usage', body: 'Consultez l’usage réel et le solde sans conversion opaque de points virtuels.' }], codeLabel: 'cURL rapide', links: { overview: 'Vue d’ensemble', billing: 'Auth et facturation', models: 'Modèles', fiveMinutes: 'Commencer en 5 minutes' } },
    quickstart: { title: 'Démarrage rapide', description: 'Effectuez votre premier appel API gpt88.cc en 5 minutes en changeant uniquement le Base URL et la clé API.', headings: { key: 'Obtenir une clé API', endpoints: 'Endpoints', curl: 'Requête cURL', sdk: 'SDK officiel', next: 'Étapes suivantes' }, keyBody: 'Créez une clé API dans la console et exportez-la dans votre environnement de terminal.', endpointBody: 'Utilisez la route standard pour le texte et le multimodal, et la route média pour les tâches image et vidéo.', endpointStandard: 'APIs standard OpenAI, Claude, Gemini et audio.', endpointMedia: 'APIs directes image et vidéo.', curlBody: 'Envoyez une requête de chat minimale pour vérifier la clé, la route et le modèle.', sdkBody: 'Tout SDK compatible OpenAI peut pointer son base_url vers la route standard.', nextBody: 'Consultez ensuite la référence API, le catalogue des modèles ou la facturation.', nextLinks: { api: 'Lire la référence Chat Completions', models: 'Parcourir les modèles', billing: 'Voir auth et facturation' } },
    core: { overview: { title: 'Vue d’ensemble', description: 'Vue d’ensemble de la passerelle IA unifiée gpt88.cc.', heading: 'Une intégration pour plusieurs modèles IA', body: 'gpt88.cc fournit une entrée compatible OpenAI pour comparer des modèles, changer de fournisseur et déplacer une application entre plusieurs routes.', bullets: ['Un modèle commun de Base URL et de clé API.', 'Comparez capacité, latence et coût dans le catalogue.', 'Choisissez une route standard, directe internationale ou CDN internationale.'] }, auth: { title: 'Auth et facturation', description: 'Authentification, sécurité des clés, facturation à l’usage et quotas.', heading: 'Protéger les identifiants et suivre l’usage réel', body: 'Utilisez Bearer pour chaque requête. Stockez les clés dans des variables d’environnement ou un gestionnaire de secrets et vérifiez la console.', bullets: ['N’exposez jamais la clé API dans le navigateur ou un dépôt public.', 'Révoquez immédiatement toute clé compromise.', 'La console fait foi pour les prix, modèles, quotas et routes.'] }, faq: { title: 'FAQ', description: 'Questions sur la compatibilité, les routes, la facturation et le dépannage.', heading: 'Réponses avant le premier appel en production', body: 'L’API est conçue pour les clients et SDK compatibles OpenAI. Commencez avec la route standard et vérifiez le modèle avec GET /v1/models.', bullets: ['Il suffit généralement de changer le Base URL et la clé API.', 'Les modèles, prix et limites dépendent du compte.', 'Utilisez un backoff exponentiel pour les limites et erreurs temporaires.'] } },
  },
}

const SIMPLE_LOCALE_OVERRIDES: Partial<Record<Locale, Partial<LocaleCopy>>> = {
  de: { siteName: 'gpt88.cc API-Dokumentation', menu: 'Sprache', nav: { docs: 'Dokumentation', quickstart: 'Schnellstart', api: 'API-Referenz', models: 'Modelle', community: 'Community', getStarted: 'Starten' }, home: { eyebrow: 'Einheitliches API-Gateway · OpenAI-kompatibel', title: 'Eine base_url für alle gpt88.cc Modelle', description: 'Nutze GPT, Claude, Gemini, DeepSeek, Qwen und Bildmodelle über eine OpenAI-kompatible API. Ändere Base URL und API-Key und behalte dein SDK.', quickstart: 'Schnellstart', getKey: 'API-Key erhalten', apiReference: 'API-Referenz', cards: [{ title: 'Minimale Migration', body: 'Base URL und API-Key ändern, Anfrageformat beibehalten.' }, { title: 'Ein Gateway, viele Modelle', body: 'Chat-, Bild-, Video- und Audiomodelle über einen Integrationsweg nutzen.' }, { title: 'Nutzungsbasierte Abrechnung', body: 'Tatsächliche Nutzung und Guthaben klar nachvollziehen.' }], codeLabel: 'Schnelles cURL', links: { overview: 'Überblick', billing: 'Auth und Abrechnung', models: 'Modelle', fiveMinutes: 'In 5 Minuten starten' } } },
  ar: { siteName: 'وثائق API ‏gpt88.cc', menu: 'اللغة', nav: { docs: 'الوثائق', quickstart: 'البدء السريع', api: 'مرجع API', models: 'النماذج', community: 'المجتمع', getStarted: 'ابدأ الآن' }, home: { eyebrow: 'بوابة API موحّدة · متوافقة مع OpenAI', title: 'عنوان base_url واحد لكل نماذج gpt88.cc', description: 'استخدم GPT وClaude وGemini وDeepSeek وQwen ونماذج الصور عبر API متوافق مع OpenAI. غيّر Base URL ومفتاح API واحتفظ بـ SDK الحالي.', quickstart: 'البدء السريع', getKey: 'الحصول على مفتاح API', apiReference: 'مرجع API', cards: [{ title: 'ترحيل بسيط', body: 'غيّر Base URL ومفتاح API واحتفظ بصيغة الطلب نفسها.' }, { title: 'بوابة واحدة ونماذج متعددة', body: 'بدّل بين نماذج المحادثة والصور والفيديو والصوت عبر مسار موحّد.' }, { title: 'فوترة حسب الاستخدام', body: 'تابع الاستخدام الفعلي والرصيد بوضوح.' }], codeLabel: 'cURL سريع', links: { overview: 'نظرة عامة', billing: 'المصادقة والفوترة', models: 'النماذج', fiveMinutes: 'ابدأ خلال 5 دقائق' } } },
  ja: { siteName: 'gpt88.cc API ドキュメント', menu: '言語', nav: { docs: 'ドキュメント', quickstart: 'クイックスタート', api: 'API リファレンス', models: 'モデル', community: 'コミュニティ', getStarted: '始める' }, home: { eyebrow: '統合 API ゲートウェイ · OpenAI 互換', title: 'gpt88.cc のすべてのモデルを 1 つの base_url で', description: 'GPT、Claude、Gemini、DeepSeek、Qwen、画像モデルを OpenAI 互換 API から利用できます。Base URL と API Key を変更するだけで既存 SDK を使えます。', quickstart: 'クイックスタート', getKey: 'API Key を取得', apiReference: 'API リファレンス', cards: [{ title: '最小限の移行', body: 'Base URL と API Key を変更し、OpenAI 形式のリクエストを維持します。' }, { title: '1 つのゲートウェイ、多数のモデル', body: 'チャット、画像、動画、音声モデルを同じ方法で利用できます。' }, { title: '使用量ベースの課金', body: '実際の使用量と残高を明確に確認できます。' }], codeLabel: 'クイック cURL', links: { overview: '概要', billing: '認証と課金', models: 'モデル', fiveMinutes: '5 分で開始' } } },
  id: { siteName: 'Dokumentasi API gpt88.cc', menu: 'Bahasa', nav: { docs: 'Dokumentasi', quickstart: 'Mulai cepat', api: 'Referensi API', models: 'Model', community: 'Komunitas', getStarted: 'Mulai' }, home: { eyebrow: 'Gateway API terpadu · Kompatibel dengan OpenAI', title: 'Satu base_url untuk semua model gpt88.cc', description: 'Gunakan GPT, Claude, Gemini, DeepSeek, Qwen, dan model gambar melalui API yang kompatibel dengan OpenAI. Ganti Base URL dan API Key tanpa menulis ulang SDK.', quickstart: 'Mulai cepat', getKey: 'Dapatkan API Key', apiReference: 'Referensi API', cards: [{ title: 'Migrasi minimal', body: 'Ganti Base URL dan API Key, lalu pertahankan format permintaan OpenAI.' }, { title: 'Satu gateway, banyak model', body: 'Gunakan model chat, gambar, video, dan audio dengan integrasi yang sama.' }, { title: 'Penagihan berdasarkan penggunaan', body: 'Lihat penggunaan aktual dan saldo dengan jelas.' }], codeLabel: 'cURL cepat', links: { overview: 'Ringkasan', billing: 'Auth dan penagihan', models: 'Model', fiveMinutes: 'Mulai dalam 5 menit' } } },
  ru: { siteName: 'Документация API gpt88.cc', menu: 'Язык', nav: { docs: 'Документация', quickstart: 'Быстрый старт', api: 'Справочник API', models: 'Модели', community: 'Сообщество', getStarted: 'Начать' }, home: { eyebrow: 'Единый API-шлюз · Совместим с OpenAI', title: 'Один base_url для всех моделей gpt88.cc', description: 'Используйте GPT, Claude, Gemini, DeepSeek, Qwen и модели изображений через OpenAI-совместимый API. Замените Base URL и API Key, сохранив текущий SDK.', quickstart: 'Быстрый старт', getKey: 'Получить API Key', apiReference: 'Справочник API', cards: [{ title: 'Минимальная миграция', body: 'Замените Base URL и API Key, сохранив формат запроса OpenAI.' }, { title: 'Один шлюз, много моделей', body: 'Переключайтесь между моделями чата, изображений, видео и аудио.' }, { title: 'Оплата по использованию', body: 'Прозрачно отслеживайте фактическое использование и баланс.' }], codeLabel: 'Быстрый cURL', links: { overview: 'Обзор', billing: 'Авторизация и оплата', models: 'Модели', fiveMinutes: 'Начать за 5 минут' } } },
  ko: { siteName: 'gpt88.cc API 문서', menu: '언어', nav: { docs: '문서', quickstart: '빠른 시작', api: 'API 레퍼런스', models: '모델', community: '커뮤니티', getStarted: '시작하기' }, home: { eyebrow: '통합 API 게이트웨이 · OpenAI 호환', title: 'gpt88.cc의 모든 모델을 하나의 base_url로', description: 'GPT, Claude, Gemini, DeepSeek, Qwen 및 이미지 모델을 OpenAI 호환 API로 사용하세요. Base URL과 API Key만 바꾸고 기존 SDK를 유지할 수 있습니다.', quickstart: '빠른 시작', getKey: 'API Key 받기', apiReference: 'API 레퍼런스', cards: [{ title: '최소한의 마이그레이션', body: 'Base URL과 API Key를 바꾸고 OpenAI 요청 형식을 유지하세요.' }, { title: '하나의 게이트웨이, 다양한 모델', body: '채팅, 이미지, 비디오, 오디오 모델을 같은 방식으로 전환하세요.' }, { title: '사용량 기반 과금', body: '실제 사용량과 잔액을 투명하게 확인하세요.' }], codeLabel: '빠른 cURL', links: { overview: '개요', billing: '인증 및 과금', models: '모델', fiveMinutes: '5분 안에 시작' } } },
  vi: { siteName: 'Tài liệu API gpt88.cc', menu: 'Ngôn ngữ', nav: { docs: 'Tài liệu', quickstart: 'Bắt đầu nhanh', api: 'Tham chiếu API', models: 'Mô hình', community: 'Cộng đồng', getStarted: 'Bắt đầu' }, home: { eyebrow: 'Cổng API hợp nhất · Tương thích OpenAI', title: 'Một base_url cho mọi mô hình trên gpt88.cc', description: 'Dùng GPT, Claude, Gemini, DeepSeek, Qwen và mô hình hình ảnh qua API tương thích OpenAI. Chỉ cần đổi Base URL và API Key, giữ nguyên SDK hiện tại.', quickstart: 'Bắt đầu nhanh', getKey: 'Lấy API Key', apiReference: 'Tham chiếu API', cards: [{ title: 'Di chuyển tối thiểu', body: 'Đổi Base URL và API Key, giữ nguyên cấu trúc request OpenAI.' }, { title: 'Một cổng, nhiều mô hình', body: 'Chuyển giữa mô hình chat, ảnh, video và audio bằng cùng một cách tích hợp.' }, { title: 'Tính phí theo sử dụng', body: 'Theo dõi mức dùng thực tế và số dư rõ ràng.' }], codeLabel: 'cURL nhanh', links: { overview: 'Tổng quan', billing: 'Xác thực và tính phí', models: 'Mô hình', fiveMinutes: 'Bắt đầu trong 5 phút' } } },
  hi: { siteName: 'gpt88.cc API दस्तावेज़', menu: 'भाषा', nav: { docs: 'दस्तावेज़', quickstart: 'त्वरित शुरुआत', api: 'API संदर्भ', models: 'मॉडल', community: 'समुदाय', getStarted: 'शुरू करें' }, home: { eyebrow: 'एकीकृत API गेटवे · OpenAI संगत', title: 'gpt88.cc के सभी मॉडल के लिए एक base_url', description: 'GPT, Claude, Gemini, DeepSeek, Qwen और इमेज मॉडल को OpenAI-संगत API से उपयोग करें। Base URL और API Key बदलकर मौजूदा SDK रखें।', quickstart: 'त्वरित शुरुआत', getKey: 'API Key पाएं', apiReference: 'API संदर्भ', cards: [{ title: 'न्यूनतम माइग्रेशन', body: 'Base URL और API Key बदलें, OpenAI अनुरोध प्रारूप बनाए रखें।' }, { title: 'एक गेटवे, कई मॉडल', body: 'चैट, इमेज, वीडियो और ऑडियो मॉडल एक ही तरीके से बदलें।' }, { title: 'उपयोग आधारित बिलिंग', body: 'वास्तविक उपयोग और बैलेंस स्पष्ट रूप से देखें।' }], codeLabel: 'त्वरित cURL', links: { overview: 'अवलोकन', billing: 'प्रमाणीकरण और बिलिंग', models: 'मॉडल', fiveMinutes: '5 मिनट में शुरू करें' } } },
  bn: { siteName: 'gpt88.cc API ডকুমেন্টেশন', menu: 'ভাষা', nav: { docs: 'ডকুমেন্টেশন', quickstart: 'দ্রুত শুরু', api: 'API রেফারেন্স', models: 'মডেল', community: 'কমিউনিটি', getStarted: 'শুরু করুন' }, home: { eyebrow: 'ইউনিফাইড API গেটওয়ে · OpenAI সামঞ্জস্যপূর্ণ', title: 'gpt88.cc-এর সব মডেলের জন্য একটি base_url', description: 'OpenAI-সামঞ্জস্যপূর্ণ API দিয়ে GPT, Claude, Gemini, DeepSeek, Qwen ও ছবি মডেল ব্যবহার করুন। শুধু Base URL ও API Key বদলান।', quickstart: 'দ্রুত শুরু', getKey: 'API Key নিন', apiReference: 'API রেফারেন্স', cards: [{ title: 'ন্যূনতম মাইগ্রেশন', body: 'Base URL ও API Key বদলে OpenAI অনুরোধের কাঠামো রাখুন।' }, { title: 'এক গেটওয়ে, বহু মডেল', body: 'চ্যাট, ছবি, ভিডিও ও অডিও মডেল একই ইন্টিগ্রেশনে বদলান।' }, { title: 'ব্যবহারভিত্তিক বিলিং', body: 'বাস্তব ব্যবহার ও ব্যালেন্স পরিষ্কারভাবে দেখুন।' }], codeLabel: 'দ্রুত cURL', links: { overview: 'ওভারভিউ', billing: 'প্রমাণীকরণ ও বিলিং', models: 'মডেল', fiveMinutes: '৫ মিনিটে শুরু করুন' } } },
  ur: { siteName: 'gpt88.cc API دستاویزات', menu: 'زبان', nav: { docs: 'دستاویزات', quickstart: 'فوری آغاز', api: 'API حوالہ', models: 'ماڈلز', community: 'کمیونٹی', getStarted: 'شروع کریں' }, home: { eyebrow: 'یونیفائیڈ API گیٹ وے · OpenAI-compatible', title: 'gpt88.cc کے تمام ماڈلز کے لیے ایک base_url', description: 'OpenAI-compatible API کے ذریعے GPT، Claude، Gemini، DeepSeek، Qwen اور امیج ماڈلز استعمال کریں۔ صرف Base URL اور API Key بدلیں۔', quickstart: 'فوری آغاز', getKey: 'API Key حاصل کریں', apiReference: 'API حوالہ', cards: [{ title: 'کم سے کم منتقلی', body: 'Base URL اور API Key بدلیں اور OpenAI درخواست کا فارمیٹ برقرار رکھیں۔' }, { title: 'ایک گیٹ وے، کئی ماڈلز', body: 'چیٹ، تصویر، ویڈیو اور آڈیو ماڈلز ایک ہی انٹیگریشن سے بدلیں۔' }, { title: 'استعمال کے مطابق بلنگ', body: 'حقیقی استعمال اور بیلنس واضح طور پر دیکھیں۔' }], codeLabel: 'فوری cURL', links: { overview: 'جائزہ', billing: 'تصدیق اور بلنگ', models: 'ماڈلز', fiveMinutes: '5 منٹ میں شروع کریں' } } },
  ta: { siteName: 'gpt88.cc API ஆவணங்கள்', menu: 'மொழி', nav: { docs: 'ஆவணங்கள்', quickstart: 'விரைவு தொடக்கம்', api: 'API குறிப்பு', models: 'மாடல்கள்', community: 'சமூகம்', getStarted: 'தொடங்குங்கள்' }, home: { eyebrow: 'ஒருங்கிணைந்த API கேட்வே · OpenAI இணக்கமானது', title: 'gpt88.cc இன் அனைத்து மாடல்களுக்கும் ஒரு base_url', description: 'OpenAI-இணக்கமான API மூலம் GPT, Claude, Gemini, DeepSeek, Qwen மற்றும் பட மாடல்களைப் பயன்படுத்துங்கள். Base URL மற்றும் API Key மட்டும் மாற்றுங்கள்.', quickstart: 'விரைவு தொடக்கம்', getKey: 'API Key பெறுக', apiReference: 'API குறிப்பு', cards: [{ title: 'குறைந்த மாற்றம்', body: 'Base URL மற்றும் API Key மாற்றி OpenAI கோரிக்கை வடிவத்தை வைத்திருங்கள்.' }, { title: 'ஒரு கேட்வே, பல மாடல்கள்', body: 'அரட்டை, படம், வீடியோ மற்றும் ஆடியோ மாடல்களை ஒரே முறையில் மாற்றுங்கள்.' }, { title: 'பயன்பாட்டு அடிப்படையிலான கட்டணம்', body: 'உண்மையான பயன்பாடு மற்றும் இருப்பைத் தெளிவாகப் பாருங்கள்.' }], codeLabel: 'விரைவு cURL', links: { overview: 'மேலோட்டம்', billing: 'அங்கீகாரம் மற்றும் கட்டணம்', models: 'மாடல்கள்', fiveMinutes: '5 நிமிடங்களில் தொடங்குங்கள்' } } },
  ne: { siteName: 'gpt88.cc API कागजात', menu: 'भाषा', nav: { docs: 'कागजात', quickstart: 'छिटो सुरु', api: 'API सन्दर्भ', models: 'मोडेल', community: 'समुदाय', getStarted: 'सुरु गर्नुहोस्' }, home: { eyebrow: 'एकीकृत API गेटवे · OpenAI compatible', title: 'gpt88.cc का सबै मोडेलका लागि एउटा base_url', description: 'OpenAI-compatible API बाट GPT, Claude, Gemini, DeepSeek, Qwen र इमेज मोडेल प्रयोग गर्नुहोस्। Base URL र API Key मात्र बदल्नुहोस्।', quickstart: 'छिटो सुरु', getKey: 'API Key लिनुहोस्', apiReference: 'API सन्दर्भ', cards: [{ title: 'न्यूनतम माइग्रेसन', body: 'Base URL र API Key बदल्नुहोस् र OpenAI अनुरोध ढाँचा राख्नुहोस्।' }, { title: 'एउटा गेटवे, धेरै मोडेल', body: 'च्याट, तस्वीर, भिडियो र अडियो मोडेल एउटै इन्टिग्रेसनबाट बदल्नुहोस्।' }, { title: 'प्रयोगमा आधारित बिलिङ', body: 'वास्तविक प्रयोग र ब्यालेन्स स्पष्ट रूपमा हेर्नुहोस्।' }], codeLabel: 'छिटो cURL', links: { overview: 'अवलोकन', billing: 'प्रमाणीकरण र बिलिङ', models: 'मोडेल', fiveMinutes: '5 मिनेटमा सुरु गर्नुहोस्' } } },
  si: { siteName: 'gpt88.cc API ලේඛන', menu: 'භාෂාව', nav: { docs: 'ලේඛන', quickstart: 'ඉක්මන් ආරම්භය', api: 'API යොමුව', models: 'මොඩල', community: 'ප්‍රජාව', getStarted: 'ආරම්භ කරන්න' }, home: { eyebrow: 'ඒකාබද්ධ API ගේට්වේ · OpenAI අනුකූල', title: 'gpt88.cc හි සියලු මොඩල සඳහා එක් base_url', description: 'OpenAI-අනුකූල API හරහා GPT, Claude, Gemini, DeepSeek, Qwen සහ රූප මොඩල භාවිත කරන්න. Base URL සහ API Key පමණක් වෙනස් කරන්න.', quickstart: 'ඉක්මන් ආරම්භය', getKey: 'API Key ලබාගන්න', apiReference: 'API යොමුව', cards: [{ title: 'අවම සංක්‍රමණය', body: 'Base URL සහ API Key වෙනස් කර OpenAI ඉල්ලීම් ආකෘතිය තබාගන්න.' }, { title: 'එක් ගේට්වේ, මොඩල රැසක්', body: 'චැට්, රූප, වීඩියෝ සහ ශ්‍රව්‍ය මොඩල එකම ඒකාබද්ධ කිරීමකින් මාරු කරන්න.' }, { title: 'භාවිතය මත පදනම් වූ බිල්පත්', body: 'සැබෑ භාවිතය සහ ශේෂය පැහැදිලිව බලන්න.' }], codeLabel: 'ඉක්මන් cURL', links: { overview: 'දළ විශ්ලේෂණය', billing: 'සත්‍යාපනය සහ බිල්පත්', models: 'මොඩල', fiveMinutes: 'මිනිත්තු 5කින් ආරම්භ කරන්න' } } },
}

const SIMPLE_CORE_COPY: Partial<Record<Locale, Partial<LocaleCopy>>> = {
  de: {
    quickstart: { title: 'Schnellstart', description: 'Führe deinen ersten gpt88.cc API-Aufruf in 5 Minuten aus, indem du nur Base URL und API-Key änderst.', headings: { key: 'API-Key erhalten', endpoints: 'Endpunkte', curl: 'cURL-Anfrage', sdk: 'Offizielles SDK', next: 'Nächste Schritte' }, keyBody: 'Erstelle einen API-Key in der Konsole und exportiere ihn in deine Terminal-Umgebung.', endpointBody: 'Verwende die Standardroute für Text und Multimodalität und die Medienroute für direkte Bild- und Videoaufgaben.', endpointStandard: 'Standard-APIs für OpenAI, Claude, Gemini und Audio.', endpointMedia: 'Direkte Bild- und Video-APIs.', curlBody: 'Sende eine minimale Chat-Anfrage, um Schlüssel, Route und Modell zu prüfen.', sdkBody: 'Jedes OpenAI-kompatible SDK kann seine base_url auf die Standardroute zeigen lassen.', nextBody: 'Lies anschließend die API-Referenz, den Modellkatalog oder die Abrechnungsanleitung.', nextLinks: { api: 'Chat-Completions-Referenz lesen', models: 'Verfügbare Modelle ansehen', billing: 'Auth und Abrechnung prüfen' } },
    core: { overview: { title: 'Überblick', description: 'Überblick über das einheitliche KI-API-Gateway von gpt88.cc.', heading: 'Eine Integration für viele KI-Modelle', body: 'gpt88.cc bietet einen OpenAI-kompatiblen Einstiegspunkt zum Vergleichen von Modellen, Wechseln von Providern und Ausführen bestehender Anwendungen über verschiedene Routen.', bullets: ['Ein gemeinsames Muster für Base URL und API-Key.', 'Fähigkeit, Latenz und Kosten im Modellkatalog vergleichen.', 'Standardroute, direkte internationale Route oder internationale CDN-Route wählen.'] }, auth: { title: 'Auth und Abrechnung', description: 'Authentifizierung, API-Key-Sicherheit, nutzungsbasierte Abrechnung und Quoten.', heading: 'Zugangsdaten schützen und echte Nutzung verfolgen', body: 'Verwende Bearer für jede Anfrage. Speichere Schlüssel in Umgebungsvariablen oder einem Secret Manager und prüfe die aktuellen Werte in der Konsole.', bullets: ['API-Key niemals im Browser oder öffentlichen Repository veröffentlichen.', 'Kompromittierte Schlüssel sofort widerrufen.', 'Preise, Modelle, Quoten und Routen in der Konsole bestätigen.'] }, faq: { title: 'FAQ', description: 'Häufige Fragen zu Kompatibilität, Routen, Abrechnung und Fehlerbehebung.', heading: 'Antworten vor dem ersten Produktionsaufruf', body: 'Die API ist für OpenAI-kompatible Clients und SDKs ausgelegt. Starte mit der Standardroute und prüfe die Modell-ID mit GET /v1/models.', bullets: ['Meist müssen nur Base URL und API-Key geändert werden.', 'Modelle, Preise und Limits hängen vom Konto ab.', 'Bei Limits und temporären Fehlern exponentielles Backoff verwenden.'] } },
  },
  ar: {
    quickstart: { title: 'البدء السريع', description: 'نفّذ أول طلب API إلى gpt88.cc خلال 5 دقائق بتغيير Base URL ومفتاح API فقط.', headings: { key: 'الحصول على مفتاح API', endpoints: 'نقاط النهاية', curl: 'طلب cURL', sdk: 'حزمة SDK الرسمية', next: 'الخطوات التالية' }, keyBody: 'أنشئ مفتاح API في لوحة التحكم ثم صدّره إلى بيئة الطرفية.', endpointBody: 'استخدم المسار القياسي للنص والطلبات متعددة الوسائط، ومسار الوسائط لمهام الصور والفيديو المباشرة.', endpointStandard: 'واجهات OpenAI وClaude وGemini والصوت القياسية.', endpointMedia: 'واجهات الصور والفيديو المباشرة.', curlBody: 'أرسل طلب محادثة بسيطاً للتحقق من المفتاح والمسار ومعرّف النموذج.', sdkBody: 'يمكن لأي SDK متوافق مع OpenAI توجيه base_url إلى المسار القياسي.', nextBody: 'تابع إلى مرجع API أو كتالوج النماذج أو دليل الفوترة.', nextLinks: { api: 'قراءة مرجع Chat Completions', models: 'تصفح النماذج المتاحة', billing: 'مراجعة المصادقة والفوترة' } },
    core: { overview: { title: 'نظرة عامة', description: 'نظرة عامة على بوابة gpt88.cc الموحدة للذكاء الاصطناعي.', heading: 'تكامل واحد لنماذج ذكاء اصطناعي متعددة', body: 'توفر gpt88.cc نقطة دخول متوافقة مع OpenAI لمقارنة النماذج وتغيير المزودين ونقل التطبيقات بين المسارات.', bullets: ['استخدم نمطاً موحداً لـ Base URL ومفتاح API.', 'قارن القدرة وزمن الاستجابة والتكلفة من كتالوج النماذج.', 'اختر المسار القياسي أو المباشر الدولي أو CDN الدولي.'] }, auth: { title: 'المصادقة والفوترة', description: 'المصادقة وأمان مفاتيح API والفوترة حسب الاستخدام والحصص.', heading: 'احمِ بيانات الاعتماد وتابع الاستخدام الفعلي', body: 'استخدم Bearer في كل طلب، واحفظ المفاتيح في متغيرات البيئة أو مدير أسرار، وارجع إلى وحدة التحكم للقيم الحالية.', bullets: ['لا تعرض مفتاح API في المتصفح أو مستودع عام.', 'ألغِ المفتاح المتسرب فوراً.', 'تحقق من الأسعار والنماذج والحصص والمسارات في وحدة التحكم.'] }, faq: { title: 'الأسئلة الشائعة', description: 'أسئلة حول التوافق والمسارات والفوترة والأمان وحل المشكلات.', heading: 'إجابات قبل أول طلب إنتاج', body: 'صُممت API للعمل مع عملاء وحزم SDK المتوافقة مع OpenAI. ابدأ بالمسار القياسي وتحقق من النموذج عبر GET /v1/models.', bullets: ['غالباً يكفي تغيير Base URL ومفتاح API.', 'تختلف النماذج والأسعار والحدود حسب الحساب.', 'استخدم التراجع الأسي مع حدود المعدل والأخطاء المؤقتة.'] } },
  },
  ja: {
    quickstart: { title: 'クイックスタート', description: 'Base URL と API Key だけを変更して、5 分で最初の gpt88.cc API リクエストを実行します。', headings: { key: 'API Key を取得', endpoints: 'エンドポイント', curl: 'cURL リクエスト', sdk: '公式 SDK', next: '次のステップ' }, keyBody: 'コンソールで API Key を作成し、ターミナルの環境変数に設定します。', endpointBody: 'テキストとマルチモーダルには標準ルート、画像と動画の直接処理にはメディアルートを使います。', endpointStandard: 'OpenAI、Claude、Gemini、音声の標準 API。', endpointMedia: '画像と動画の直接 API。', curlBody: '最小のチャットリクエストで Key、ルート、モデル ID を確認します。', sdkBody: 'OpenAI 互換 SDK の base_url を標準ルートに設定して利用できます。', nextBody: 'API リファレンス、モデル一覧、課金ガイドを続けて確認してください。', nextLinks: { api: 'Chat Completions リファレンスを読む', models: '利用可能なモデルを見る', billing: '認証と課金を確認する' } },
    core: { overview: { title: '概要', description: 'gpt88.cc 統合 AI API ゲートウェイの概要。', heading: '多くの AI モデルを 1 つの方法で利用', body: 'gpt88.cc はモデル比較、プロバイダー切り替え、既存アプリのルート変更に使える OpenAI 互換の入口を提供します。', bullets: ['Base URL と API Key の形式を統一。', 'モデル一覧で能力、レイテンシ、コストを比較。', '標準、海外直結、海外 CDN ルートを選択。'] }, auth: { title: '認証と課金', description: '認証、API Key の安全、使用量課金、クォータの説明。', heading: '認証情報を守り、実際の使用量を確認', body: 'すべてのリクエストで Bearer 認証を使います。Key は環境変数または Secret Manager に保存し、最新の値はコンソールで確認してください。', bullets: ['API Key をブラウザや公開リポジトリに出さない。', '漏洩した Key はすぐに無効化する。', '価格、モデル、クォータ、ルートはコンソールを確認する。'] }, faq: { title: 'よくある質問', description: '互換性、ルート、課金、安全性、トラブルシューティングに関する質問。', heading: '本番リクエスト前に確認する回答', body: 'OpenAI 互換クライアントと SDK 向けの API です。標準ルートから始め、GET /v1/models でモデル ID を確認してください。', bullets: ['通常は Base URL と API Key の変更だけで利用できます。', 'モデル、価格、制限はアカウントによって異なります。', '制限や一時的な障害には指数バックオフを使います。'] } },
  },
  id: {
    quickstart: { title: 'Mulai cepat', description: 'Lakukan panggilan API gpt88.cc pertama dalam 5 menit dengan mengganti Base URL dan API Key.', headings: { key: 'Dapatkan API Key', endpoints: 'Endpoint', curl: 'Permintaan cURL', sdk: 'SDK resmi', next: 'Langkah berikutnya' }, keyBody: 'Buat API Key di konsol, lalu ekspor ke lingkungan terminal.', endpointBody: 'Gunakan rute standar untuk teks dan multimodal, serta rute media untuk tugas gambar dan video langsung.', endpointStandard: 'API standar OpenAI, Claude, Gemini, dan audio.', endpointMedia: 'API gambar dan video langsung.', curlBody: 'Kirim permintaan chat minimal untuk memeriksa key, rute, dan ID model.', sdkBody: 'SDK apa pun yang kompatibel dengan OpenAI dapat mengarahkan base_url ke rute standar.', nextBody: 'Lanjutkan ke referensi API, katalog model, atau panduan penagihan.', nextLinks: { api: 'Baca referensi Chat Completions', models: 'Lihat model yang tersedia', billing: 'Tinjau autentikasi dan penagihan' } },
    core: { overview: { title: 'Ringkasan', description: 'Ringkasan gateway API AI terpadu gpt88.cc.', heading: 'Satu integrasi untuk banyak model AI', body: 'gpt88.cc menyediakan pintu masuk yang kompatibel dengan OpenAI untuk membandingkan model, mengganti provider, dan menjalankan aplikasi melalui rute berbeda.', bullets: ['Gunakan pola Base URL dan API Key yang sama.', 'Bandingkan kemampuan, latensi, dan biaya di katalog model.', 'Pilih rute standar, direct internasional, atau CDN internasional.'] }, auth: { title: 'Auth dan penagihan', description: 'Autentikasi, keamanan API Key, penagihan berdasarkan penggunaan, dan kuota.', heading: 'Lindungi kredensial dan lacak penggunaan aktual', body: 'Gunakan Bearer pada setiap permintaan. Simpan key di environment variable atau secret manager dan cek nilai terbaru di konsol.', bullets: ['Jangan tampilkan API Key di browser atau repositori publik.', 'Cabut key yang bocor segera.', 'Konfirmasi harga, model, kuota, dan rute di konsol.'] }, faq: { title: 'Pertanyaan umum', description: 'Pertanyaan tentang kompatibilitas, rute, penagihan, keamanan, dan troubleshooting.', heading: 'Jawaban sebelum permintaan produksi pertama', body: 'API ini ditujukan untuk klien dan SDK yang kompatibel dengan OpenAI. Mulai dari rute standar dan verifikasi model dengan GET /v1/models.', bullets: ['Biasanya cukup mengganti Base URL dan API Key.', 'Model, harga, dan batas bergantung pada akun.', 'Gunakan exponential backoff untuk rate limit dan kegagalan sementara.'] } },
  },
  ru: {
    quickstart: { title: 'Быстрый старт', description: 'Выполните первый запрос к API gpt88.cc за 5 минут, изменив только Base URL и API Key.', headings: { key: 'Получить API Key', endpoints: 'Конечные точки', curl: 'Запрос cURL', sdk: 'Официальный SDK', next: 'Следующие шаги' }, keyBody: 'Создайте API Key в консоли и экспортируйте его в окружение терминала.', endpointBody: 'Для текста и мультимодальности используйте стандартный маршрут, для прямых задач с изображениями и видео — медиамаршрут.', endpointStandard: 'Стандартные API OpenAI, Claude, Gemini и аудио.', endpointMedia: 'Прямые API изображений и видео.', curlBody: 'Отправьте минимальный чат-запрос, чтобы проверить ключ, маршрут и ID модели.', sdkBody: 'Любой OpenAI-совместимый SDK может использовать стандартный маршрут в base_url.', nextBody: 'Затем откройте справочник API, каталог моделей или руководство по оплате.', nextLinks: { api: 'Открыть справочник Chat Completions', models: 'Посмотреть доступные модели', billing: 'Проверить авторизацию и оплату' } },
    core: { overview: { title: 'Обзор', description: 'Обзор единого AI API-шлюза gpt88.cc.', heading: 'Одна интеграция для множества AI-моделей', body: 'gpt88.cc предоставляет OpenAI-совместимую точку входа для сравнения моделей, смены провайдера и работы приложения через разные маршруты.', bullets: ['Единый формат Base URL и API Key.', 'Сравнение возможностей, задержки и стоимости в каталоге.', 'Стандартный, прямой международный или CDN-маршрут.'] }, auth: { title: 'Авторизация и оплата', description: 'Авторизация, безопасность API Key, оплата по использованию и квоты.', heading: 'Защищайте ключи и отслеживайте фактическое использование', body: 'Используйте Bearer в каждом запросе. Храните ключи в переменных окружения или менеджере секретов, а актуальные значения проверяйте в консоли.', bullets: ['Не публикуйте API Key в браузере или открытом репозитории.', 'Немедленно отзывайте скомпрометированный ключ.', 'Цены, модели, квоты и маршруты проверяйте в консоли.'] }, faq: { title: 'Частые вопросы', description: 'Вопросы о совместимости, маршрутах, оплате, безопасности и устранении ошибок.', heading: 'Ответы перед первым production-запросом', body: 'API предназначен для OpenAI-совместимых клиентов и SDK. Начните со стандартного маршрута и проверьте модель через GET /v1/models.', bullets: ['Обычно достаточно изменить Base URL и API Key.', 'Модели, цены и лимиты зависят от аккаунта.', 'Для лимитов и временных ошибок используйте exponential backoff.'] } },
  },
  ko: {
    quickstart: { title: '빠른 시작', description: 'Base URL과 API Key만 변경하여 5분 안에 첫 gpt88.cc API 요청을 실행하세요.', headings: { key: 'API Key 받기', endpoints: '엔드포인트', curl: 'cURL 요청', sdk: '공식 SDK', next: '다음 단계' }, keyBody: '콘솔에서 API Key를 만든 후 터미널 환경 변수로 내보내세요.', endpointBody: '텍스트와 멀티모달에는 표준 경로를, 직접 이미지와 비디오 작업에는 미디어 경로를 사용하세요.', endpointStandard: 'OpenAI, Claude, Gemini, 오디오 표준 API.', endpointMedia: '직접 이미지 및 비디오 API.', curlBody: '최소 채팅 요청으로 키, 경로, 모델 ID를 확인하세요.', sdkBody: 'OpenAI 호환 SDK의 base_url을 표준 경로로 지정하면 됩니다.', nextBody: 'API 레퍼런스, 모델 카탈로그, 과금 가이드를 계속 확인하세요.', nextLinks: { api: 'Chat Completions 레퍼런스 읽기', models: '사용 가능한 모델 보기', billing: '인증 및 과금 확인' } },
    core: { overview: { title: '개요', description: 'gpt88.cc 통합 AI API 게이트웨이 개요.', heading: '하나의 통합 방식으로 여러 AI 모델 사용', body: 'gpt88.cc는 모델 비교, 제공업체 전환, 기존 애플리케이션의 경로 변경을 위한 OpenAI 호환 진입점을 제공합니다.', bullets: ['Base URL과 API Key 형식을 통일합니다.', '모델 카탈로그에서 기능, 지연 시간, 비용을 비교합니다.', '표준, 해외 직결, 해외 CDN 경로를 선택합니다.'] }, auth: { title: '인증 및 과금', description: '인증, API Key 보안, 사용량 기반 과금, 할당량 안내.', heading: '자격 증명을 보호하고 실제 사용량 확인', body: '모든 요청에 Bearer 인증을 사용하세요. Key는 환경 변수나 Secret Manager에 저장하고 최신 값은 콘솔에서 확인합니다.', bullets: ['브라우저나 공개 저장소에 API Key를 노출하지 않습니다.', '유출된 Key는 즉시 폐기합니다.', '가격, 모델, 할당량, 경로는 콘솔에서 확인합니다.'] }, faq: { title: '자주 묻는 질문', description: '호환성, 경로, 과금, 보안, 문제 해결에 관한 질문.', heading: '첫 운영 요청 전에 확인할 답변', body: 'OpenAI 호환 클라이언트와 SDK를 위한 API입니다. 표준 경로로 시작하고 GET /v1/models로 모델 ID를 확인하세요.', bullets: ['대부분 Base URL과 API Key만 바꾸면 됩니다.', '모델, 가격, 한도는 계정에 따라 다릅니다.', '한도와 일시적 장애에는 지수 백오프를 사용합니다.'] } },
  },
  vi: {
    quickstart: { title: 'Bắt đầu nhanh', description: 'Thực hiện request API gpt88.cc đầu tiên trong 5 phút bằng cách chỉ đổi Base URL và API Key.', headings: { key: 'Lấy API Key', endpoints: 'Endpoint', curl: 'Request cURL', sdk: 'SDK chính thức', next: 'Bước tiếp theo' }, keyBody: 'Tạo API Key trong bảng điều khiển và export vào môi trường terminal.', endpointBody: 'Dùng route tiêu chuẩn cho văn bản và đa phương thức, route media cho tác vụ ảnh và video trực tiếp.', endpointStandard: 'API tiêu chuẩn cho OpenAI, Claude, Gemini và audio.', endpointMedia: 'API ảnh và video trực tiếp.', curlBody: 'Gửi request chat tối thiểu để kiểm tra key, route và model ID.', sdkBody: 'Mọi SDK tương thích OpenAI đều có thể trỏ base_url tới route tiêu chuẩn.', nextBody: 'Tiếp tục đọc tham chiếu API, danh mục mô hình hoặc hướng dẫn tính phí.', nextLinks: { api: 'Đọc tham chiếu Chat Completions', models: 'Xem mô hình khả dụng', billing: 'Xem xác thực và tính phí' } },
    core: { overview: { title: 'Tổng quan', description: 'Tổng quan về cổng API AI hợp nhất gpt88.cc.', heading: 'Một cách tích hợp cho nhiều mô hình AI', body: 'gpt88.cc cung cấp điểm vào tương thích OpenAI để so sánh mô hình, đổi nhà cung cấp và chạy ứng dụng qua nhiều route.', bullets: ['Dùng chung định dạng Base URL và API Key.', 'So sánh khả năng, độ trễ và chi phí trong danh mục mô hình.', 'Chọn route tiêu chuẩn, direct quốc tế hoặc CDN quốc tế.'] }, auth: { title: 'Xác thực và tính phí', description: 'Xác thực, bảo mật API Key, tính phí theo sử dụng và hạn mức.', heading: 'Bảo vệ thông tin xác thực và theo dõi mức dùng thực tế', body: 'Dùng Bearer cho mọi request. Lưu key trong biến môi trường hoặc secret manager và kiểm tra giá trị hiện tại trong console.', bullets: ['Không để lộ API Key trong trình duyệt hoặc kho công khai.', 'Thu hồi ngay key bị lộ.', 'Xác nhận giá, mô hình, hạn mức và route trong console.'] }, faq: { title: 'Câu hỏi thường gặp', description: 'Câu hỏi về tương thích, route, tính phí, bảo mật và xử lý lỗi.', heading: 'Câu trả lời trước request production đầu tiên', body: 'API dành cho client và SDK tương thích OpenAI. Bắt đầu với route tiêu chuẩn và kiểm tra model ID bằng GET /v1/models.', bullets: ['Thông thường chỉ cần đổi Base URL và API Key.', 'Mô hình, giá và giới hạn phụ thuộc tài khoản.', 'Dùng exponential backoff cho rate limit và lỗi tạm thời.'] } },
  },
  hi: {
    quickstart: { title: 'त्वरित शुरुआत', description: 'केवल Base URL और API Key बदलकर 5 मिनट में पहला gpt88.cc API अनुरोध भेजें।', headings: { key: 'API Key प्राप्त करें', endpoints: 'एंडपॉइंट', curl: 'cURL अनुरोध', sdk: 'आधिकारिक SDK', next: 'अगले कदम' }, keyBody: 'कंसोल में API Key बनाएं और उसे टर्मिनल के environment variable में export करें।', endpointBody: 'टेक्स्ट और multimodal अनुरोधों के लिए मानक route तथा सीधे image और video कार्यों के लिए media route उपयोग करें।', endpointStandard: 'मानक OpenAI, Claude, Gemini और audio API।', endpointMedia: 'सीधे image और video API।', curlBody: 'Key, route और model ID की पुष्टि के लिए एक छोटा chat अनुरोध भेजें।', sdkBody: 'किसी भी OpenAI-compatible SDK में base_url को standard route पर सेट करें।', nextBody: 'API reference, model catalog और billing guide देखें।', nextLinks: { api: 'Chat Completions API reference पढ़ें', models: 'उपलब्ध मॉडल देखें', billing: 'प्रमाणीकरण और billing देखें' } },
    core: { overview: { title: 'अवलोकन', description: 'gpt88.cc unified AI API gateway का व्यावहारिक परिचय।', heading: 'कई AI मॉडल के लिए एक integration path', body: 'gpt88.cc OpenAI-compatible प्रवेश बिंदु देता है, जिससे developer मॉडल की तुलना, provider बदलने और मौजूदा application को अलग routes पर चलाने में सक्षम होते हैं।', bullets: ['एक Base URL और API Key pattern उपयोग करें।', 'Model catalog में capability, latency और cost की तुलना करें।', 'ज़रूरत के अनुसार standard, overseas direct या overseas CDN route चुनें।'] }, auth: { title: 'प्रमाणीकरण और billing', description: 'Authentication, API Key safety, usage billing और quota guidance।', heading: 'Credentials को server-side रखें और वास्तविक उपयोग देखें', body: 'हर अनुरोध में Bearer authentication उपयोग करें। Keys को environment variable या secret manager में रखें और वर्तमान model, pricing, quota तथा route के लिए console देखें।', bullets: ['API Key को browser code या public repository में expose न करें।', 'लीक हुई Key को तुरंत revoke और rotate करें।', 'Billing और quota के लिए वर्तमान console record को source of truth मानें।'] }, faq: { title: 'अक्सर पूछे जाने वाले प्रश्न', description: 'Compatibility, routes, billing, security और troubleshooting से जुड़े सामान्य प्रश्न।', heading: 'पहले production अनुरोध से पहले उत्तर', body: 'API OpenAI-compatible clients और SDKs के लिए बनाई गई है। Standard route से शुरू करें, GET /v1/models से model ID जांचें और troubleshooting में request ID रखें।', bullets: ['अधिकांश OpenAI SDK में केवल Base URL और API Key बदलनी होती है।', 'Models, pricing और quotas account-specific हैं।', 'Rate limits और अस्थायी failures के लिए exponential backoff उपयोग करें।'] } },
  },
  bn: {
    quickstart: { title: 'দ্রুত শুরু', description: 'শুধু Base URL এবং API Key বদলে ৫ মিনিটে প্রথম gpt88.cc API অনুরোধ পাঠান।', headings: { key: 'API Key নিন', endpoints: 'এন্ডপয়েন্ট', curl: 'cURL অনুরোধ', sdk: 'অফিশিয়াল SDK', next: 'পরবর্তী ধাপ' }, keyBody: 'কনসোলে API Key তৈরি করে টার্মিনালের environment variable-এ export করুন।', endpointBody: 'টেক্সট ও multimodal অনুরোধে standard route এবং সরাসরি ছবি ও ভিডিও কাজে media route ব্যবহার করুন।', endpointStandard: 'স্ট্যান্ডার্ড OpenAI, Claude, Gemini ও audio API।', endpointMedia: 'সরাসরি ছবি ও ভিডিও API।', curlBody: 'Key, route এবং model ID যাচাই করতে একটি ছোট chat অনুরোধ পাঠান।', sdkBody: 'যেকোনো OpenAI-compatible SDK-তে base_url standard route-এ সেট করুন।', nextBody: 'API reference, model catalog ও billing guide দেখুন।', nextLinks: { api: 'Chat Completions API reference পড়ুন', models: 'উপলব্ধ মডেল দেখুন', billing: 'প্রমাণীকরণ ও billing দেখুন' } },
    core: { overview: { title: 'ওভারভিউ', description: 'gpt88.cc unified AI API gateway-এর ব্যবহারিক পরিচিতি।', heading: 'অনেক AI মডেলের জন্য একটি integration path', body: 'gpt88.cc একটি OpenAI-compatible প্রবেশপথ দেয়, যাতে developer মডেল তুলনা, provider বদল এবং বিদ্যমান application বিভিন্ন route-এ চালাতে পারেন।', bullets: ['একটি Base URL ও API Key pattern ব্যবহার করুন।', 'Model catalog-এ capability, latency ও cost তুলনা করুন।', 'প্রয়োজনে standard, overseas direct বা overseas CDN route বেছে নিন।'] }, auth: { title: 'প্রমাণীকরণ ও billing', description: 'Authentication, API Key safety, usage billing ও quota guidance।', heading: 'Credentials server-side রাখুন এবং প্রকৃত ব্যবহার দেখুন', body: 'প্রতিটি অনুরোধে Bearer authentication ব্যবহার করুন। Key environment variable বা secret manager-এ রাখুন এবং বর্তমান তথ্যের জন্য console দেখুন।', bullets: ['Browser code বা public repository-তে API Key প্রকাশ করবেন না।', 'ফাঁস হওয়া Key সঙ্গে সঙ্গে revoke ও rotate করুন।', 'Billing ও quota-র জন্য বর্তমান console record-কে source of truth ধরুন।'] }, faq: { title: 'সাধারণ প্রশ্ন', description: 'Compatibility, route, billing, security ও troubleshooting সম্পর্কিত প্রশ্ন।', heading: 'প্রথম production অনুরোধের আগে উত্তর', body: 'API OpenAI-compatible client ও SDK-এর জন্য তৈরি। Standard route দিয়ে শুরু করুন এবং GET /v1/models দিয়ে model ID যাচাই করুন।', bullets: ['সাধারণত Base URL ও API Key বদলালেই হয়।', 'Model, pricing ও quota account-specific।', 'Rate limit ও সাময়িক ব্যর্থতায় exponential backoff ব্যবহার করুন।'] } },
  },
  ur: {
    quickstart: { title: 'فوری آغاز', description: 'صرف Base URL اور API Key بدل کر 5 منٹ میں پہلی gpt88.cc API درخواست بھیجیں۔', headings: { key: 'API Key حاصل کریں', endpoints: 'اینڈ پوائنٹس', curl: 'cURL درخواست', sdk: 'آفیشل SDK', next: 'اگلے مراحل' }, keyBody: 'کنسول میں API Key بنائیں اور اسے ٹرمینل کے environment variable میں export کریں۔', endpointBody: 'ٹیکسٹ اور multimodal درخواستوں کے لیے standard route، جبکہ براہ راست image اور video کاموں کے لیے media route استعمال کریں۔', endpointStandard: 'معیاری OpenAI، Claude، Gemini اور audio APIs۔', endpointMedia: 'براہ راست image اور video APIs۔', curlBody: 'Key، route اور model ID کی تصدیق کے لیے مختصر chat درخواست بھیجیں۔', sdkBody: 'کسی بھی OpenAI-compatible SDK میں base_url کو standard route پر سیٹ کریں۔', nextBody: 'API reference، model catalog اور billing guide دیکھیں۔', nextLinks: { api: 'Chat Completions API reference پڑھیں', models: 'دستیاب ماڈلز دیکھیں', billing: 'تصدیق اور billing دیکھیں' } },
    core: { overview: { title: 'جائزہ', description: 'gpt88.cc unified AI API gateway کا عملی تعارف۔', heading: 'متعدد AI ماڈلز کے لیے ایک integration path', body: 'gpt88.cc ایک OpenAI-compatible داخلی راستہ فراہم کرتا ہے، جس سے ماڈلز کا موازنہ، provider کی تبدیلی اور موجودہ application کو مختلف routes پر چلانا ممکن ہے۔', bullets: ['ایک Base URL اور API Key pattern استعمال کریں۔', 'Model catalog میں capability، latency اور cost کا موازنہ کریں۔', 'ضرورت کے مطابق standard، overseas direct یا overseas CDN route منتخب کریں۔'] }, auth: { title: 'تصدیق اور billing', description: 'Authentication، API Key safety، usage billing اور quota guidance۔', heading: 'Credentials server-side رکھیں اور حقیقی استعمال دیکھیں', body: 'ہر درخواست میں Bearer authentication استعمال کریں۔ Keys کو environment variable یا secret manager میں رکھیں اور موجودہ معلومات کے لیے console دیکھیں۔', bullets: ['API Key کو browser code یا public repository میں ظاہر نہ کریں۔', 'لیک ہونے والی Key کو فوراً revoke اور rotate کریں۔', 'Billing اور quota کے لیے موجودہ console record کو source of truth سمجھیں۔'] }, faq: { title: 'اکثر پوچھے گئے سوالات', description: 'Compatibility، routes، billing، security اور troubleshooting کے عام سوالات۔', heading: 'پہلی production درخواست سے پہلے جوابات', body: 'API OpenAI-compatible clients اور SDKs کے لیے ہے۔ Standard route سے شروع کریں اور GET /v1/models سے model ID کی تصدیق کریں۔', bullets: ['عام طور پر صرف Base URL اور API Key بدلنی ہوتی ہے۔', 'Models، pricing اور quotas account-specific ہیں۔', 'Rate limits اور عارضی ناکامیوں کے لیے exponential backoff استعمال کریں۔'] } },
  },
  ta: {
    quickstart: { title: 'விரைவு தொடக்கம்', description: 'Base URL மற்றும் API Key மட்டும் மாற்றி 5 நிமிடங்களில் முதல் gpt88.cc API கோரிக்கையை அனுப்புங்கள்.', headings: { key: 'API Key பெறுக', endpoints: 'எண்ட்பாயிண்ட்கள்', curl: 'cURL கோரிக்கை', sdk: 'அதிகாரப்பூர்வ SDK', next: 'அடுத்த படிகள்' }, keyBody: 'கன்சோலில் API Key உருவாக்கி terminal environment variable-ஆக export செய்யவும்.', endpointBody: 'உரை மற்றும் multimodal கோரிக்கைகளுக்கு standard route-ஐ, நேரடி படம் மற்றும் வீடியோ பணிகளுக்கு media route-ஐப் பயன்படுத்தவும்.', endpointStandard: 'நிலையான OpenAI, Claude, Gemini மற்றும் audio APIகள்.', endpointMedia: 'நேரடி படம் மற்றும் வீடியோ APIகள்.', curlBody: 'Key, route மற்றும் model ID-ஐ சரிபார்க்க குறைந்தபட்ச chat கோரிக்கையை அனுப்பவும்.', sdkBody: 'எந்த OpenAI-compatible SDK-யிலும் base_url-ஐ standard route-க்கு அமைக்கலாம்.', nextBody: 'API reference, model catalog மற்றும் billing guide-ஐத் தொடரவும்.', nextLinks: { api: 'Chat Completions API reference படிக்கவும்', models: 'கிடைக்கும் மாடல்களைப் பார்க்கவும்', billing: 'அங்கீகாரம் மற்றும் billing பார்க்கவும்' } },
    core: { overview: { title: 'மேலோட்டம்', description: 'gpt88.cc unified AI API gateway-ன் நடைமுறை அறிமுகம்.', heading: 'பல AI மாடல்களுக்கு ஒரே integration path', body: 'gpt88.cc OpenAI-compatible நுழைவாயிலை வழங்குகிறது; இதன் மூலம் மாடல்களை ஒப்பிட்டு, provider-ஐ மாற்றி, ஏற்கனவே உள்ள application-ஐ பல routes-ல் இயக்கலாம்.', bullets: ['ஒரே Base URL மற்றும் API Key pattern பயன்படுத்தவும்.', 'Model catalog-ல் capability, latency மற்றும் cost ஒப்பிடவும்.', 'தேவைக்கேற்ப standard, overseas direct அல்லது overseas CDN route தேர்வு செய்யவும்.'] }, auth: { title: 'அங்கீகாரம் மற்றும் billing', description: 'Authentication, API Key safety, usage billing மற்றும் quota guidance.', heading: 'Credentials-ஐ server-side வைத்து உண்மையான பயன்பாட்டைக் கண்காணிக்கவும்', body: 'ஒவ்வொரு கோரிக்கையிலும் Bearer authentication பயன்படுத்தவும். Keys-ஐ environment variable அல்லது secret manager-ல் வைத்து, தற்போதைய தகவல்களுக்கு console-ஐப் பார்க்கவும்.', bullets: ['API Key-ஐ browser code அல்லது public repository-ல் வெளியிட வேண்டாம்.', 'கசிந்த Key-ஐ உடனே revoke மற்றும் rotate செய்யவும்.', 'Billing மற்றும் quota-க்கு தற்போதைய console record-ஐ ஆதாரமாகக் கொள்ளவும்.'] }, faq: { title: 'அடிக்கடி கேட்கப்படும் கேள்விகள்', description: 'Compatibility, routes, billing, security மற்றும் troubleshooting பற்றிய கேள்விகள்.', heading: 'முதல் production கோரிக்கைக்கு முன் பதில்கள்', body: 'API OpenAI-compatible clients மற்றும் SDKகளுக்காக வடிவமைக்கப்பட்டுள்ளது. Standard route-ல் தொடங்கி GET /v1/models மூலம் model ID-ஐச் சரிபார்க்கவும்.', bullets: ['பொதுவாக Base URL மற்றும் API Key மட்டும் மாற்ற வேண்டும்.', 'Models, pricing மற்றும் quotas கணக்கைப் பொறுத்தவை.', 'Rate limit மற்றும் தற்காலிக தோல்விகளுக்கு exponential backoff பயன்படுத்தவும்.'] } },
  },
  ne: {
    quickstart: { title: 'छिटो सुरु', description: 'Base URL र API Key मात्र बदलेर ५ मिनेटमा पहिलो gpt88.cc API अनुरोध पठाउनुहोस्।', headings: { key: 'API Key लिनुहोस्', endpoints: 'एन्डपोइन्ट', curl: 'cURL अनुरोध', sdk: 'आधिकारिक SDK', next: 'अर्का चरण' }, keyBody: 'कन्सोलमा API Key बनाएर terminal environment variable मा export गर्नुहोस्।', endpointBody: 'टेक्स्ट र multimodal अनुरोधका लागि standard route र प्रत्यक्ष image/video कामका लागि media route प्रयोग गर्नुहोस्।', endpointStandard: 'मानक OpenAI, Claude, Gemini र audio API।', endpointMedia: 'प्रत्यक्ष image र video API।', curlBody: 'Key, route र model ID जाँच्न छोटो chat अनुरोध पठाउनुहोस्।', sdkBody: 'कुनै पनि OpenAI-compatible SDK मा base_url लाई standard route मा सेट गर्नुहोस्।', nextBody: 'API reference, model catalog र billing guide हेर्नुहोस्।', nextLinks: { api: 'Chat Completions API reference पढ्नुहोस्', models: 'उपलब्ध मोडेल हेर्नुहोस्', billing: 'प्रमाणीकरण र billing हेर्नुहोस्' } },
    core: { overview: { title: 'अवलोकन', description: 'gpt88.cc unified AI API gateway को व्यावहारिक परिचय।', heading: 'धेरै AI मोडेलका लागि एउटै integration path', body: 'gpt88.cc ले OpenAI-compatible प्रवेशद्वार दिन्छ, जसबाट developer ले मोडेल तुलना, provider परिवर्तन र application लाई फरक routes मा चलाउन सक्छन्।', bullets: ['एउटै Base URL र API Key pattern प्रयोग गर्नुहोस्।', 'Model catalog मा capability, latency र cost तुलना गर्नुहोस्।', 'आवश्यकताअनुसार standard, overseas direct वा overseas CDN route छान्नुहोस्।'] }, auth: { title: 'प्रमाणीकरण र billing', description: 'Authentication, API Key safety, usage billing र quota guidance।', heading: 'Credentials server-side राख्नुहोस् र वास्तविक प्रयोग हेर्नुहोस्', body: 'हरेक अनुरोधमा Bearer authentication प्रयोग गर्नुहोस्। Keys लाई environment variable वा secret manager मा राख्नुहोस् र हालको जानकारीका लागि console हेर्नुहोस्।', bullets: ['API Key लाई browser code वा public repository मा नराख्नुहोस्।', 'लिक भएको Key तुरुन्त revoke र rotate गर्नुहोस्।', 'Billing र quota का लागि हालको console record लाई source of truth मान्नुहोस्।'] }, faq: { title: 'सामान्य प्रश्न', description: 'Compatibility, routes, billing, security र troubleshooting सम्बन्धी प्रश्न।', heading: 'पहिलो production अनुरोधअघि उत्तर', body: 'API OpenAI-compatible client र SDK का लागि बनाइएको हो। Standard route बाट सुरु गरी GET /v1/models बाट model ID जाँच्नुहोस्।', bullets: ['सामान्यतया Base URL र API Key मात्र बदल्नुपर्छ।', 'Models, pricing र quotas account-specific हुन्छन्।', 'Rate limits र अस्थायी failures का लागि exponential backoff प्रयोग गर्नुहोस्।'] } },
  },
  si: {
    quickstart: { title: 'ඉක්මන් ආරම්භය', description: 'Base URL සහ API Key පමණක් වෙනස් කර මිනිත්තු 5කින් පළමු gpt88.cc API ඉල්ලීම යවන්න.', headings: { key: 'API Key ලබාගන්න', endpoints: 'එන්ඩ්පොයින්ට්', curl: 'cURL ඉල්ලීම', sdk: 'නිල SDK', next: 'ඊළඟ පියවර' }, keyBody: 'කොන්සෝලයේ API Key එකක් සාදා terminal environment variable එකකට export කරන්න.', endpointBody: 'පෙළ සහ multimodal ඉල්ලීම් සඳහා standard route එකත්, සෘජු රූප සහ වීඩියෝ කාර්ය සඳහා media route එකත් භාවිත කරන්න.', endpointStandard: 'සම්මත OpenAI, Claude, Gemini සහ audio API.', endpointMedia: 'සෘජු රූප සහ වීඩියෝ API.', curlBody: 'Key, route සහ model ID පරීක්ෂා කිරීමට කෙටි chat ඉල්ලීමක් යවන්න.', sdkBody: 'ඕනෑම OpenAI-compatible SDK එකක base_url එක standard route වෙත සකසන්න.', nextBody: 'API reference, model catalog සහ billing guide වෙත යන්න.', nextLinks: { api: 'Chat Completions API reference කියවන්න', models: 'ලබාගත හැකි මොඩල බලන්න', billing: 'සත්‍යාපනය සහ billing බලන්න' } },
    core: { overview: { title: 'දළ විශ්ලේෂණය', description: 'gpt88.cc unified AI API gateway පිළිබඳ ප්‍රායෝගික හැඳින්වීම.', heading: 'AI මොඩල රැසකට එක integration path එකක්', body: 'gpt88.cc OpenAI-compatible ප්‍රවේශයක් ලබා දෙයි. එමඟින් මොඩල සසඳා, provider වෙනස් කර, පවතින application විවිධ routes මත ධාවනය කළ හැකිය.', bullets: ['එක් Base URL සහ API Key pattern එකක් භාවිත කරන්න.', 'Model catalog තුළ capability, latency සහ cost සසඳන්න.', 'අවශ්‍යතාවයට අනුව standard, overseas direct හෝ overseas CDN route තෝරන්න.'] }, auth: { title: 'සත්‍යාපනය සහ billing', description: 'Authentication, API Key safety, usage billing සහ quota guidance.', heading: 'Credentials server-side තබා සැබෑ භාවිතය නිරීක්ෂණය කරන්න', body: 'සෑම ඉල්ලීමකම Bearer authentication භාවිත කරන්න. Keys environment variable හෝ secret manager එකක තබා වත්මන් තොරතුරු සඳහා console පරීක්ෂා කරන්න.', bullets: ['API Key browser code හෝ public repository තුළ පෙන්වන්න එපා.', 'කාන්දු වූ Key එක වහාම revoke සහ rotate කරන්න.', 'Billing සහ quota සඳහා වත්මන් console record එක source of truth ලෙස ගන්න.'] }, faq: { title: 'නිතර අසන ප්‍රශ්න', description: 'Compatibility, routes, billing, security සහ troubleshooting පිළිබඳ ප්‍රශ්න.', heading: 'පළමු production ඉල්ලීමට පෙර පිළිතුරු', body: 'API OpenAI-compatible clients සහ SDK සඳහා නිර්මාණය කර ඇත. Standard route එකෙන් ආරම්භ කර GET /v1/models මඟින් model ID පරීක්ෂා කරන්න.', bullets: ['සාමාන්‍යයෙන් Base URL සහ API Key පමණක් වෙනස් කළ යුතුය.', 'Models, pricing සහ quotas ගිණුම අනුව වෙනස් වේ.', 'Rate limits සහ තාවකාලික failures සඳහා exponential backoff භාවිත කරන්න.'] } },
  },
}

function mergeCopy(base: LocaleCopy, override: Partial<LocaleCopy>): LocaleCopy {
  return {
    ...base,
    ...override,
    nav: { ...base.nav, ...override.nav },
    home: { ...base.home, ...override.home, links: { ...base.home.links, ...override.home?.links } },
    quickstart: { ...base.quickstart, ...override.quickstart, headings: { ...base.quickstart.headings, ...override.quickstart?.headings }, nextLinks: { ...base.quickstart.nextLinks, ...override.quickstart?.nextLinks } },
    core: {
      ...base.core,
      ...override.core,
      overview: { ...base.core.overview, ...override.core?.overview },
      auth: { ...base.core.auth, ...override.core?.auth },
      faq: { ...base.core.faq, ...override.core?.faq },
    },
  }
}

export function getLocaleCopy(locale: Locale): LocaleCopy {
  const override = TRANSLATIONS[locale] ?? SIMPLE_LOCALE_OVERRIDES[locale as keyof typeof SIMPLE_LOCALE_OVERRIDES] ?? {}
  const coreOverride = SIMPLE_CORE_COPY[locale as keyof typeof SIMPLE_CORE_COPY]
  return mergeCopy(mergeCopy(EN, override), coreOverride ?? {})
}
