import type { Locale } from './locale'

type SdkKind = 'curl' | 'python' | 'nodejs'
type SdkCopy = { title: string; description: string; intro: string; sections: Record<string, string> }

const COPY: Partial<Record<Locale, Record<SdkKind, SdkCopy>>> = {
  hi: { curl: { title: 'cURL उदाहरण', description: 'cURL से gpt88.cc API को verify, script और CI health check करें।', intro: 'पहले API Key और endpoint जांचें, फिर model list और एक छोटा request चलाएं।', sections: { check: 'स्वास्थ्य जांच', list: 'मॉडल सूची', chat: 'chat/completions कॉल', stream: 'स्ट्रीमिंग प्रतिक्रिया', retry: 'बैकऑफ रीट्राई स्क्रिप्ट' } }, python: { title: 'Python से GPT88 API कॉल', description: 'OpenAI Python SDK से GPT88 API कॉल करें; इसमें sync, streaming और error handling शामिल है।', intro: 'OpenAI SDK को बनाए रखते हुए केवल base_url और API Key बदलकर शुरुआत करें।', sections: { install: 'इंस्टॉल और कॉन्फ़िगरेशन', basic: 'मूल कॉल', stream: 'स्ट्रीमिंग प्रतिक्रिया', tools: 'function calling', errors: 'त्रुटि प्रबंधन और रीट्राई', async: 'असिंक्रोनस उपयोग' } }, nodejs: { title: 'Node.js से GPT88 API कॉल', description: 'Node.js में OpenAI SDK से GPT88 API कॉल करें; environment variables, streaming और retry शामिल हैं।', intro: 'Server-side environment में Key रखें और मौजूदा OpenAI-compatible client से request भेजें।', sections: { install: 'इंस्टॉल और कॉन्फ़िगरेशन', basic: 'मूल कॉल', stream: 'स्ट्रीमिंग प्रतिक्रिया', retry: 'बैकऑफ रीट्राई', edge: 'Edge / serverless' } } },
  bn: { curl: { title: 'cURL উদাহরণ', description: 'cURL দিয়ে gpt88.cc API যাচাই, script এবং CI health check করুন।', intro: 'প্রথমে API Key ও endpoint যাচাই করুন, তারপর model list এবং একটি ছোট request চালান।', sections: { check: 'স্বাস্থ্য পরীক্ষা', list: 'মডেল তালিকা', chat: 'chat/completions কল', stream: 'স্ট্রিমিং প্রতিক্রিয়া', retry: 'ব্যাকঅফ রিট্রাই স্ক্রিপ্ট' } }, python: { title: 'Python দিয়ে GPT88 API কল', description: 'OpenAI Python SDK দিয়ে GPT88 API কল করুন; sync, streaming ও error handling অন্তর্ভুক্ত।', intro: 'OpenAI SDK রেখে শুধু base_url ও API Key বদলে শুরু করুন।', sections: { install: 'ইনস্টল ও কনফিগারেশন', basic: 'মৌলিক কল', stream: 'স্ট্রিমিং প্রতিক্রিয়া', tools: 'function calling', errors: 'ত্রুটি পরিচালনা ও রিট্রাই', async: 'অ্যাসিঙ্ক্রোনাস ব্যবহার' } }, nodejs: { title: 'Node.js দিয়ে GPT88 API কল', description: 'Node.js-এ OpenAI SDK দিয়ে GPT88 API কল করুন; environment variable, streaming ও retry অন্তর্ভুক্ত।', intro: 'Key server-side environment-এ রাখুন এবং বিদ্যমান OpenAI-compatible client দিয়ে request পাঠান।', sections: { install: 'ইনস্টল ও কনফিগারেশন', basic: 'মৌলিক কল', stream: 'স্ট্রিমিং প্রতিক্রিয়া', retry: 'ব্যাকঅফ রিট্রাই', edge: 'Edge / serverless' } } },
  ur: { curl: { title: 'cURL مثال', description: 'cURL سے gpt88.cc API کو verify، script اور CI health check کریں۔', intro: 'پہلے API Key اور endpoint چیک کریں، پھر model list اور مختصر request چلائیں۔', sections: { check: 'ہیلتھ چیک', list: 'ماڈلز کی فہرست', chat: 'chat/completions کال', stream: 'اسٹریمنگ جواب', retry: 'بیک آف ری ٹرائی اسکرپٹ' } }, python: { title: 'Python سے GPT88 API کال', description: 'OpenAI Python SDK سے GPT88 API کال کریں؛ sync، streaming اور error handling شامل ہیں۔', intro: 'OpenAI SDK برقرار رکھتے ہوئے صرف base_url اور API Key تبدیل کر کے شروع کریں۔', sections: { install: 'انسٹالیشن اور کنفیگریشن', basic: 'بنیادی کال', stream: 'اسٹریمنگ جواب', tools: 'function calling', errors: 'غلطی کا انتظام اور ری ٹرائی', async: 'غیر متزامن استعمال' } }, nodejs: { title: 'Node.js سے GPT88 API کال', description: 'Node.js میں OpenAI SDK سے GPT88 API کال کریں؛ environment variables، streaming اور retry شامل ہیں۔', intro: 'Key کو server-side environment میں رکھیں اور موجودہ OpenAI-compatible client سے request بھیجیں۔', sections: { install: 'انسٹالیشن اور کنفیگریشن', basic: 'بنیادی کال', stream: 'اسٹریمنگ جواب', retry: 'بیک آف ری ٹرائی', edge: 'Edge / serverless' } } },
  ta: { curl: { title: 'cURL எடுத்துக்காட்டு', description: 'cURL மூலம் gpt88.cc API-ஐச் சரிபார்த்து, script மற்றும் CI health check செய்யவும்.', intro: 'முதலில் API Key மற்றும் endpoint-ஐச் சரிபார்த்து, பின்னர் model list மற்றும் குறைந்தபட்ச request இயக்கவும்.', sections: { check: 'சுகாதாரச் சரிபார்ப்பு', list: 'மாதிரி பட்டியல்', chat: 'chat/completions அழைப்பு', stream: 'ஸ்ட்ரீமிங் பதில்', retry: 'பின்வாங்கல் மீண்டும் முயற்சி ஸ்கிரிப்ட்' } }, python: { title: 'Python மூலம் GPT88 API அழைப்பு', description: 'OpenAI Python SDK மூலம் GPT88 API-ஐ அழைக்கவும்; sync, streaming மற்றும் error handling அடங்கும்.', intro: 'OpenAI SDK-ஐ வைத்துக்கொண்டு base_url மற்றும் API Key மட்டும் மாற்றி தொடங்கவும்.', sections: { install: 'நிறுவல் மற்றும் கட்டமைப்பு', basic: 'அடிப்படை அழைப்பு', stream: 'ஸ்ட்ரீமிங் பதில்', tools: 'function calling', errors: 'பிழை கையாளல் மற்றும் மீண்டும் முயற்சி', async: 'ஒத்திசைவற்ற பயன்பாடு' } }, nodejs: { title: 'Node.js மூலம் GPT88 API அழைப்பு', description: 'Node.js-ல் OpenAI SDK மூலம் GPT88 API-ஐ அழைக்கவும்; environment variables, streaming மற்றும் retry அடங்கும்.', intro: 'Key-ஐ server-side environment-ல் வைத்து ஏற்கனவே உள்ள OpenAI-compatible client-ஐப் பயன்படுத்தவும்.', sections: { install: 'நிறுவல் மற்றும் கட்டமைப்பு', basic: 'அடிப்படை அழைப்பு', stream: 'ஸ்ட்ரீமிங் பதில்', retry: 'பின்வாங்கல் மீண்டும் முயற்சி', edge: 'Edge / serverless' } } },
  ne: { curl: { title: 'cURL उदाहरण', description: 'cURL बाट gpt88.cc API verify, script र CI health check गर्नुहोस्।', intro: 'पहिले API Key र endpoint जाँच्नुहोस्, त्यसपछि model list र छोटो request चलाउनुहोस्।', sections: { check: 'स्वास्थ्य जाँच', list: 'मोडेल सूची', chat: 'chat/completions कल', stream: 'स्ट्रिमिङ प्रतिक्रिया', retry: 'ब्याकअफ रिट्राई स्क्रिप्ट' } }, python: { title: 'Python बाट GPT88 API कल', description: 'OpenAI Python SDK बाट GPT88 API कल गर्नुहोस्; sync, streaming र error handling समावेश छन्।', intro: 'OpenAI SDK राखेर base_url र API Key मात्र बदलेर सुरु गर्नुहोस्।', sections: { install: 'इन्स्टल र कन्फिगरेसन', basic: 'आधारभूत कल', stream: 'स्ट्रिमिङ प्रतिक्रिया', tools: 'function calling', errors: 'त्रुटि व्यवस्थापन र रिट्राई', async: 'असिन्क्रोनस प्रयोग' } }, nodejs: { title: 'Node.js बाट GPT88 API कल', description: 'Node.js मा OpenAI SDK बाट GPT88 API कल गर्नुहोस्; environment variables, streaming र retry समावेश छन्।', intro: 'Key लाई server-side environment मा राखी विद्यमान OpenAI-compatible client प्रयोग गर्नुहोस्।', sections: { install: 'इन्स्टल र कन्फिगरेसन', basic: 'आधारभूत कल', stream: 'स्ट्रिमिङ प्रतिक्रिया', retry: 'ब्याकअफ रिट्राई', edge: 'Edge / serverless' } } },
  si: { curl: { title: 'cURL උදාහරණය', description: 'cURL මඟින් gpt88.cc API verify, script සහ CI health check කරන්න.', intro: 'පළමුව API Key සහ endpoint පරීක්ෂා කර, පසුව model list සහ කෙටි request එකක් ධාවනය කරන්න.', sections: { check: 'සෞඛ්‍ය පරීක්ෂාව', list: 'මාදිලි ලැයිස්තුව', chat: 'chat/completions ඇමතුම', stream: 'ප්‍රවාහ ප්‍රතිචාරය', retry: 'backoff retry ස්ක්‍රිප්ට්' } }, python: { title: 'Python මඟින් GPT88 API ඇමතුම', description: 'OpenAI Python SDK මඟින් GPT88 API අමතන්න; sync, streaming සහ error handling ඇතුළත්ය.', intro: 'OpenAI SDK තබාගෙන base_url සහ API Key පමණක් වෙනස් කර ආරම්භ කරන්න.', sections: { install: 'ස්ථාපනය සහ වින්‍යාසය', basic: 'මූලික ඇමතුම', stream: 'ප්‍රවාහ ප්‍රතිචාරය', tools: 'function calling', errors: 'දෝෂ හැසිරවීම සහ retry', async: 'අසමමුහුර්ත භාවිතය' } }, nodejs: { title: 'Node.js මඟින් GPT88 API ඇමතුම', description: 'Node.js තුළ OpenAI SDK මඟින් GPT88 API අමතන්න; environment variables, streaming සහ retry ඇතුළත්ය.', intro: 'Key server-side environment එකක තබා පවතින OpenAI-compatible client එක භාවිත කරන්න.', sections: { install: 'ස්ථාපනය සහ වින්‍යාසය', basic: 'මූලික ඇමතුම', stream: 'ප්‍රවාහ ප්‍රතිචාරය', retry: 'backoff retry', edge: 'Edge / serverless' } } },
}

export function getSdkCopy(locale: Locale, kind: SdkKind, fallback: SdkCopy): SdkCopy {
  return COPY[locale]?.[kind] ?? fallback
}
