import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Compass,
  Cpu,
  ExternalLink,
  Info,
  Layers,
  Rocket,
  SearchX,
  Star,
  Tag,
  Target,
} from 'lucide-react'
import { CodeTabs, type CodeTab } from '../components/ui/CodeTabs'
import { CodeBlock } from '../components/ui/CodeBlock'
import { Callout } from '../components/ui/Callout'
import { EndpointBadge } from '../components/ui/EndpointBadge'
import { FieldTable, type FieldRow } from '../components/ui/FieldTable'
import {
  CATEGORY_META,
  MODELS,
  findModel,
  type ModelEntry,
} from '../data/models'
import { Seo } from '../components/seo/Seo'
import { modelStructuredData } from '../components/seo/structuredData'
import { localizePath, useLocale } from '../lib/locale'

/**
 * 模型详情页 (M3 + Human msg-20260509-qoz7ey/jwfia3/8ivlof 全量 catalog)
 *
 * 路由：/models/:slug
 *
 * 信息架构（参考 apimart 详情页心智，UI 不照搬）：
 * 1) Hero：模型名 + provider + tagline + 主 CTA「在 gpt88.cc 获取 API Key」(外链)
 *    + 次 CTA「快速开始」(站内 Link) + 复制 modelId 胶囊
 * 2) 关键信息卡（侧栏）：modelId / provider / category / vendors_count / 接口路径
 * 3) 能力标签 + 推荐场景：仅 featured 8 个有人工文案，其他模型显示「以控制台为准」
 * 4) 接口路径徽章 + 请求示例（cURL / Python / Node.js）
 * 5) 期望响应（精简 JSON 示例）
 * 6) 同分类相关模型（按 vendors_count 取前 4）
 *
 * 关于"slug 无效"的处理（QA 反馈 t-20260508-ekhzqd）：
 *
 * 早期实现是 `<Navigate to="/models/" replace />`，纯客户端重定向。
 * 它依赖两个前提：
 *   1) 客户端 JS 能正常加载（react-router 需要先渲染才能触发 Navigate）；
 *   2) 托管平台已经把任意路径 200 rewrite 到 index.html。
 * 如果其中任一不成立——例如 SPA fallback 漏配、或者中间有 CDN 把 404 透传，
 * 用户会看到一闪而过的空白甚至直接 404，体验非常糟糕。
 *
 * 因此现在不再"悄悄重定向"，而是显式渲染一个内嵌的"模型未找到"分支：
 *   - 给出明确中文提示和返回入口；
 *   - 即使没拿到模型数据，路由本身仍命中 /models/:slug，
 *     一旦 SPA fallback 生效，用户立即看到的是友好提示而不是空白；
 *   - 没有埋在 useEffect 里，避免 SSR / hydration 闪烁与回退被生命周期吞掉。
 *
 * 注意：本分支只解决"客户端命中路由后 slug 无对应模型"这一情况。
 * 如果 SPA rewrite 完全没配置，浏览器在拿到 index.html 之前就已 404，
 * 那是部署侧问题，需要 web/public/_redirects + vercel.json 等配合解决，
 * 详见 README 的"静态部署 SPA Fallback"段落。
 */

export default function ModelDetailPage() {
  const { slug } = useParams<{ slug: string }>()
  const model = slug ? findModel(slug) : undefined

  // 路由切换时回到顶部，避免承接上一篇详情的滚动位置
  useEffect(() => {
    window.scrollTo({ top: 0 })
  }, [slug])

  if (!model) {
    // 显式分支：渲染"模型未找到"提示，而不是悄悄 <Navigate>。
    // 这样在 SPA fallback 命中后，用户能立刻看到清晰的中文提示和回退入口。
    return <ModelNotFound slug={slug} />
  }

  return <DetailContent model={model} />
}

function DetailContent({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  const seoPath = `/models/${model.slug}`
  const seoDescription = buildModelSeoDescription(model, locale)
  const categoryTitle = localizedCategoryTitle(model.category, locale)
  const t =
    locale === 'en'
      ? {
          pageTitle: `${model.name} API Docs`,
          breadcrumb: 'Models',
          featured: 'Featured',
          vendors: 'vendors',
          getKey: 'Get API Key on gpt88.cc',
          quickstart: 'Quickstart',
          overview: 'Overview',
          whenToUse: 'Best Use Cases',
          integration: 'Integration Notes',
          caveats: 'Usage Notes',
          capabilities: 'Capabilities',
          scenarios: 'Recommended Scenarios',
          endpoint: 'Endpoint Path',
          endpointDesc:
            'The endpoint path is determined by the model category. Chat, image, video, and audio models use different endpoints.',
          requestExamples: 'Request Examples',
          pricingWarn: 'Pricing, rate limits, and SLA are not fixed on this page',
          pricingBody:
            'Pricing, concurrency limits, rate limits, and context availability may change dynamically by account level and console configuration.',
          basics: 'Basic Info',
          category: 'Category',
          upstream: 'Upstream',
          related: 'Related Models',
          back: 'Back to Models',
          provider: 'Provider',
          interface: 'Interface',
          apiDoc: 'API Docs',
          headers: 'Headers / Auth',
          requestParams: 'Request Parameters',
          responseFields: 'Response Fields',
          statusCodes: 'Status Codes',
          requestFieldsBody:
            'The fields below are generated by model category. Pricing, context limits, rate limits, and available routes should be confirmed in the gpt88.cc console.',
          responseFieldsBody:
            'Response bodies generally follow OpenAI-compatible shapes. Media models may return async task IDs or resource URLs.',
          authPrefix: 'Send requests with',
          authReferencePrefix: 'See',
          authReferenceSuffix: 'for the full parameter reference.',
          copyModel: 'Copy model id',
          copy: 'Copy',
          exactCase: 'Keep the exact model ID casing when copying.',
          missingTitle: 'Model not found',
          missingBody: 'This model may have been removed, renamed, or is not available in the current catalog.',
          viewAll: 'View all models',
          firstQuickstart: 'Open Quickstart',
        }
      : {
          pageTitle: `${model.name} API 文档`,
          breadcrumb: '模型导航',
          featured: '主推模型',
          vendors: '家上游',
          getKey: '在 gpt88.cc 获取 API Key',
          quickstart: '快速开始',
          overview: '模型概览',
          whenToUse: '适用场景',
          integration: '接入说明',
          caveats: '使用提醒',
          capabilities: '能力标签',
          scenarios: '推荐场景',
          endpoint: '接口路径',
          endpointDesc:
            '该路径由模型分类决定：Chat / Image / Video / Audio 使用不同 endpoint，同一分类内通常只需要替换 model 字段。',
          requestExamples: '请求示例',
          pricingWarn: '价格、限速、SLA 不在此页固化',
          pricingBody:
            '不同模型的单价、并发上限、限速、SLA 与可用上下文，会随账号等级与控制台配置动态调整。本页面只描述协议字段；具体数字请以 gpt88.cc 控制台为准。',
          basics: '基础信息',
          category: '分类',
          upstream: '上游',
          related: '同分类相关模型',
          back: '返回模型导航',
          provider: 'Provider',
          interface: '接口',
          apiDoc: 'API 文档',
          headers: 'Headers / 鉴权',
          requestParams: '请求参数',
          responseFields: '响应字段',
          statusCodes: '状态码',
          requestFieldsBody:
            '以下字段按当前模型分类生成。价格、上下文长度、限速、可用线路等动态信息以 gpt88.cc 控制台为准。',
          responseFieldsBody:
            '响应结构保持 OpenAI 兼容风格；媒体类模型可能返回异步任务 ID 或资源 URL。',
          authPrefix: '请求需在 Header 中携带',
          authReferencePrefix: '完整字段说明见',
          authReferenceSuffix: '。',
          copyModel: '复制 model id',
          copy: '复制',
          exactCase: '当前模型 ID：复制时请保持大小写一致。',
          missingTitle: '页面不见了',
          missingBody: '可能是模型已下线、链接拼写有误，或者还未上线。',
          viewAll: '查看全部模型',
          firstQuickstart: '先看快速开始',
        }

  // 同分类的相关模型，按 vendors_count 降序取前 4
  const related = useMemo(
    () =>
      MODELS
        .filter(m => m.category === model.category && m.slug !== model.slug)
        .sort((a, b) => b.vendorsCount - a.vendorsCount)
        .slice(0, 4),
    [model],
  )

  return (
    <>
      <Seo
        title={t.pageTitle}
        description={seoDescription}
        path={seoPath}
        type="article"
        structuredData={modelStructuredData({
          name: model.name,
          description: seoDescription,
          path: seoPath,
          provider: model.provider,
          category: model.category,
          modelId: model.modelId,
          locale,
        })}
      />
      <div className="relative isolate">
      {/* 背景光晕 */}
      <div aria-hidden className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute inset-0 bg-grid bg-grid-fade opacity-30" />
        <div className="absolute left-1/2 top-0 h-[360px] w-[640px] -translate-x-1/2 rounded-full bg-violet-600/15 blur-3xl" />
      </div>

      <section className="mx-auto max-w-7xl px-4 pb-20 pt-10 sm:px-6 lg:px-8">
        {/* 面包屑 */}
        <nav className="text-xs text-ink-400" aria-label="面包屑">
          <Link to={localizePath('/models/', locale)} className="inline-flex items-center gap-1 hover:text-ink-200">
            <ArrowLeft className="h-3 w-3" />
            {t.breadcrumb}
          </Link>
          <span className="mx-2 text-ink-600">/</span>
          <span className="text-ink-300">
            {categoryTitle}
          </span>
          <span className="mx-2 text-ink-600">/</span>
          <span className="text-ink-100">{model.name}</span>
        </nav>

        {/* Hero */}
        <header className="mt-6">
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <span className="rounded-full bg-violet-500/10 px-2 py-0.5 font-medium text-violet-200 ring-1 ring-violet-500/30">
              {categoryTitle}
            </span>
            <span className="rounded-full bg-white/5 px-2 py-0.5 text-ink-300">
              {model.provider}
            </span>
            {model.featured ? (
              <span className="inline-flex items-center gap-1 rounded-full border border-amber-400/30 bg-amber-400/10 px-2 py-0.5 font-semibold text-amber-200">
                <Star className="h-3 w-3" />
                {t.featured}
              </span>
            ) : null}
            <span className="rounded-full bg-white/5 px-2 py-0.5 text-ink-300">
              {model.vendorsCount} {t.vendors}
            </span>
          </div>

          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-ink-50 sm:text-4xl">
            {model.name}
          </h1>
          <p className="mt-3 max-w-3xl text-sm text-ink-300 sm:text-base">
            {model.tagline}
          </p>

          {/* 主 CTA / 次 CTA / 复制 modelId */}
          <div className="mt-5 flex flex-wrap items-center gap-3">
            {/*
             * 主 CTA：跳到 gpt88.cc 控制台获取 API Key。
             * 这是站点根域 gpt88.cc 本身（白名单内），用 <a target="_blank">
             * 真实跳转，不要试图用 <Link>。
             */}
            <a
              href="https://gpt88.cc"
              target="_blank"
              rel="noreferrer"
              className="group inline-flex items-center gap-2 rounded-md bg-gradient-to-r from-violet-500 to-violet-600 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-violet-600/30 transition-transform hover:scale-[1.02]"
            >
              {t.getKey}
              <ExternalLink className="h-4 w-4 opacity-80 transition-transform group-hover:translate-x-0.5" />
            </a>
            <Link
              to={localizePath('/docs/quickstart/', locale)}
              className="inline-flex items-center gap-2 rounded-md border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold text-ink-100 hover:border-violet-500/40 hover:bg-violet-500/10"
            >
              <Rocket className="h-4 w-4 text-violet-300" />
              {t.quickstart}
            </Link>
            <ModelIdPill modelId={model.modelId} />
          </div>
        </header>

        {/* 主体 */}
        <div className="mt-10 grid grid-cols-1 gap-8 lg:grid-cols-[minmax(0,1fr)_18rem]">
          {/* 左主体 */}
          <div className="min-w-0 space-y-10">
            {/*
             * Human 新需求：每个模型都要有更完整的文字介绍，而不只是标签。
             * 这里把数据层新增的 overview / whenToUse / integrationNotes / caveats
             * 渲染成四个文本区块；主推 21 个走人工精修层，其他长尾走模板层。
             * 如果未来某些模型对应数组为空，仍由 ConsoleAuthoritativeNote 兜底。
             */}
            <Section icon={Info} title={t.overview}>
              <DetailBulletList field={t.overview} items={model.overview} />
            </Section>

            <Section icon={Target} title={t.whenToUse}>
              <DetailBulletList field={t.whenToUse} items={model.whenToUse} />
            </Section>

            <Section icon={Layers} title={t.integration}>
              <DetailBulletList field={t.integration} items={model.integrationNotes} />
            </Section>

            <Section icon={Info} title={t.caveats}>
              <DetailBulletList field={t.caveats} items={model.caveats} />
            </Section>

            {/* 能力标签：紧凑标签层 */}
            <Section icon={Tag} title={t.capabilities}>
              {model.capabilities.length > 0 ? (
                <div className="flex flex-wrap gap-2">
                  {model.capabilities.map(cap => (
                    <span
                      key={cap}
                      className="rounded-full border border-violet-500/30 bg-violet-500/10 px-3 py-1 text-xs text-violet-200"
                    >
                      {cap}
                    </span>
                  ))}
                </div>
              ) : (
                <ConsoleAuthoritativeNote field={t.capabilities} />
              )}
            </Section>

            {/* 推荐场景：紧凑标签层 */}
            <Section icon={Target} title={t.scenarios}>
              {model.scenarios.length > 0 ? (
                <ul className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                  {model.scenarios.map(s => (
                    <li
                      key={s}
                      className="flex items-start gap-2 rounded-md border border-white/5 bg-white/[0.02] px-3 py-2 text-sm text-ink-200"
                    >
                      <Check className="mt-0.5 h-4 w-4 shrink-0 text-violet-300" />
                      {s}
                    </li>
                  ))}
                </ul>
              ) : (
                <ConsoleAuthoritativeNote field={t.scenarios} />
              )}
            </Section>

            {/* 接口路径 */}
            <Section icon={Layers} title={t.endpoint}>
              <div className="space-y-3">
                <EndpointBadge
                  method={model.endpoint.method}
                  path={`${apiOriginForModel(model)}${model.endpoint.path}`}
                />
                <p className="text-sm text-ink-300">
                  {t.endpointDesc}
                </p>
                <p className="text-sm text-ink-300">
                  {t.authPrefix}{' '}
                  <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-violet-200">
                    Authorization: Bearer &lt;API_KEY&gt;
                  </code>
                  。 {t.authReferencePrefix}{' '}
                  <Link to={localizePath(apiReferencePathForModel(model), locale)} className="text-violet-300 hover:text-violet-200">
                    {apiReferenceLabelForModel(model, locale)}
                  </Link>
                  {' '}{t.authReferenceSuffix}
                </p>
              </div>
            </Section>

            <ModelApiReference model={model} />

            {/* 请求示例 */}
            <Section icon={Cpu} title={t.requestExamples}>
              <ModelRequestExamples model={model} />
              <Callout tone="warn" title={t.pricingWarn}>
                <p>
                  {t.pricingBody}
                </p>
              </Callout>
              <ExpectedResponse model={model} />
            </Section>
          </div>

          {/* 右侧栏 */}
          <aside className="space-y-6 lg:sticky lg:top-20 lg:self-start">
            {/* 基础信息 */}
            <div className="tech-card p-5">
              <h3 className="text-xs font-semibold uppercase tracking-wider text-ink-400">
                {t.basics}
              </h3>
              <dl className="mt-4 space-y-3 text-sm">
                <InfoRow label={t.provider} value={model.provider} />
                <InfoRow
                  label="Model ID"
                  value={<code className="font-mono text-violet-200">{model.modelId}</code>}
                />
                <InfoRow label={t.category} value={categoryTitle} />
                <InfoRow
                  label={t.upstream}
                  value={`${model.vendorsCount} ${t.vendors}`}
                />
                <InfoRow
                  label={t.interface}
                  value={
                    <code className="font-mono text-ink-200">
                      {model.endpoint.method} {model.endpoint.path}
                    </code>
                  }
                />
              </dl>
            </div>

            {/* 同分类相关模型 */}
            {related.length > 0 ? (
              <div className="tech-card p-5">
                <h3 className="text-xs font-semibold uppercase tracking-wider text-ink-400">
                  {t.related}
                </h3>
                <ul className="mt-3 space-y-2">
                  {related.map(r => (
                    <li key={r.slug}>
                      <Link
                        to={localizePath(`/models/${r.slug}/`, locale)}
                        className="group flex items-center justify-between gap-2 rounded-md px-2 py-2 text-sm text-ink-200 hover:bg-white/5"
                      >
                        <span className="min-w-0">
                          <span className="block truncate font-medium text-ink-100 group-hover:text-violet-200">
                            {r.name}
                          </span>
                          <span className="block truncate text-[11.5px] text-ink-400">
                            {r.provider} · {r.vendorsCount} {t.vendors}
                          </span>
                        </span>
                        <ArrowRight className="h-3.5 w-3.5 shrink-0 text-ink-500 transition-transform group-hover:translate-x-0.5 group-hover:text-violet-300" />
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}

            {/* 返回模型导航 */}
            <Link
              to={localizePath('/models/', locale)}
              className="inline-flex items-center gap-1.5 text-xs font-medium text-ink-400 hover:text-ink-200"
            >
              <ArrowLeft className="h-3 w-3" />
              {t.back}
            </Link>
          </aside>
        </div>
      </section>
      </div>
    </>
  )
}

/* ──────────────────────────────────────────────────────────────────
 * 详细说明层列表
 *
 * overview / whenToUse / integrationNotes / caveats 都走这一层：
 * - 主推 21 个使用人工精修文案
 * - 长尾模型使用模板生成文案
 * - 若未来有模型对应字段为空，则回退到「以控制台为准」而不是留白
 * ────────────────────────────────────────────────────────────────── */
function DetailBulletList({
  field,
  items,
}: {
  field: string
  items: string[]
}) {
  if (items.length === 0) {
    return <ConsoleAuthoritativeNote field={field} />
  }
  return (
    <ul className="space-y-2">
      {items.map(item => (
        <li
          key={item}
          className="flex items-start gap-2 rounded-md border border-white/5 bg-white/[0.02] px-3 py-3 text-sm leading-relaxed text-ink-200"
        >
          <span className="mt-1 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-violet-300" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

/* ──────────────────────────────────────────────────────────────────
 * 「以控制台为准」占位
 *
 * 用于长尾模型的能力标签 / 推荐场景区。marketplace 快照里没有这些字段，
 * 也不能瞎猜——直接告诉读者去控制台看，避免文档与真实能力漂移。
 * ────────────────────────────────────────────────────────────────── */
function ConsoleAuthoritativeNote({ field }: { field: string }) {
  const { locale } = useLocale()
  return (
    <div className="flex items-start gap-2 rounded-md border border-white/5 bg-white/[0.02] px-3 py-3 text-sm text-ink-300">
      <Info className="mt-0.5 h-4 w-4 shrink-0 text-ink-400" />
      <p>
        {locale === 'en'
          ? `This model's ${field} should be verified in the gpt88.cc console. This page focuses on protocol shape and request examples.`
          : `该模型的${field}以 gpt88.cc 控制台为准。本页只展示协议字段与请求示例，具体能力 / 推荐场景 / 上下文长度等信息会随上游版本变更，请在 `}
        <a
          href="https://gpt88.cc"
          target="_blank"
          rel="noreferrer"
          className="text-violet-300 hover:text-violet-200"
        >
          {locale === 'en' ? 'gpt88.cc console' : 'gpt88.cc 控制台'}
        </a>{' '}
        {locale === 'en' ? 'for the real-time catalog.' : '查看实时清单。'}
      </p>
    </div>
  )
}

/* ──────────────────────────────────────────────────────────────────
 * 辅助：可复制的 Model ID 胶囊
 * ────────────────────────────────────────────────────────────────── */
function ModelIdPill({ modelId }: { modelId: string }) {
  const { locale } = useLocale()
  const [copied, setCopied] = useState(false)
  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(modelId)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      /* 复制失败时静默忽略，不打断用户 */
    }
  }
  return (
    <button
      type="button"
      onClick={onCopy}
      className="group inline-flex items-center gap-2 rounded-md border border-violet-500/30 bg-violet-500/10 px-3 py-1.5 font-mono text-xs text-violet-100 hover:bg-violet-500/15"
      aria-label={locale === 'en' ? 'Copy model id' : '复制 model id'}
      title={locale === 'en' ? 'Copy model id' : '复制 model id'}
    >
      <span className="text-ink-400">model:</span>
      <span>{modelId}</span>
      {copied ? (
        <Check className="h-3.5 w-3.5 text-emerald-300" />
      ) : (
        <span className="text-[10px] uppercase tracking-wider text-violet-300/80 group-hover:text-violet-200">
          {locale === 'en' ? 'Copy' : '复制'}
        </span>
      )}
    </button>
  )
}

function InfoRow({
  label,
  value,
}: {
  label: string
  value: React.ReactNode
}) {
  return (
    <div className="flex items-baseline justify-between gap-3">
      <dt className="text-[11.5px] uppercase tracking-wider text-ink-500">
        {label}
      </dt>
      <dd className="min-w-0 truncate text-right text-sm text-ink-100">
        {value}
      </dd>
    </div>
  )
}

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>
  title: string
  children: React.ReactNode
}) {
  return (
    <section>
      <div className="mb-4 flex items-center gap-2 border-b border-white/5 pb-2">
        <Icon className="h-4 w-4 text-violet-300" />
        <h2 className="text-base font-semibold text-ink-50">{title}</h2>
      </div>
      {children}
    </section>
  )
}

function ModelApiReference({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  return (
    <Section icon={Cpu} title={locale === 'en' ? 'API Docs' : 'API 文档'}>
      <div className="space-y-6">
        <ApiQuickFacts model={model} />
        <div>
          <h3 className="text-sm font-semibold text-ink-100">{locale === 'en' ? 'Headers / Auth' : 'Headers / 鉴权'}</h3>
          <FieldTable rows={headerFieldsForModel(model, locale)} className="mb-0 mt-3" />
        </div>
        {model.category === 'chat' ? <ChatProtocolGuide model={model} /> : null}
        <div>
          <h3 className="text-sm font-semibold text-ink-100">{locale === 'en' ? 'Request Parameters' : '请求参数'}</h3>
          <p className="mt-1 text-sm leading-relaxed text-ink-300">
            {locale === 'en'
              ? 'The fields below are generated by model category. Pricing, context limits, rate limits, and available routes should be confirmed in the gpt88.cc console.'
              : '以下字段按当前模型分类生成。价格、上下文长度、限速、可用线路等动态信息以 gpt88.cc 控制台为准。'}
          </p>
          <FieldTable rows={requestFieldsForModel(model, locale)} className="mb-0 mt-3" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-ink-100">{locale === 'en' ? 'Response Fields' : '响应字段'}</h3>
          <p className="mt-1 text-sm leading-relaxed text-ink-300">
            {locale === 'en'
              ? 'Response bodies generally follow OpenAI-compatible shapes. Media models may return async task IDs or resource URLs.'
              : '响应结构保持 OpenAI 兼容风格；媒体类模型可能返回异步任务 ID 或资源 URL。'}
          </p>
          <FieldTable rows={responseFieldsForModel(model, locale)} className="mb-0 mt-3" />
        </div>
        <div>
          <h3 className="text-sm font-semibold text-ink-100">{locale === 'en' ? 'Status Codes' : '状态码'}</h3>
          <FieldTable rows={statusCodeRows(model, locale)} className="mb-0 mt-3" />
        </div>
        <ErrorChecklist model={model} />
      </div>
    </Section>
  )
}

function ApiQuickFacts({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  const contentType =
    model.category === 'audio' ? 'multipart/form-data' : 'application/json'
  const protocolHint = protocolHintForModel(model, locale)
  const baseUrlHint =
    model.category === 'chat'
      ? chatBaseUrlHint(model, locale)
      : isGeminiImageModel(model)
        ? locale === 'en'
          ? 'Gemini-native image endpoints use the media Base URL https://img.gpt88.cc.'
          : 'Gemini 原生兼容接口使用图片与多媒体 Base URL https://img.gpt88.cc。'
      : model.category === 'image'
        ? locale === 'en'
          ? 'Image endpoints use the media Base URL https://img.gpt88.cc.'
          : '图片接口使用图片与多媒体 Base URL https://img.gpt88.cc。'
      : locale === 'en'
        ? 'Media endpoints use https://img.gpt88.cc and submit requests to the matching endpoint path.'
        : '媒体类接口使用 https://img.gpt88.cc，并按对应 endpoint 提交请求。'
  const endpointValue =
    model.category === 'chat' && isAnthropicModel(model)
      ? locale === 'en'
        ? 'POST /v1/messages or POST /v1/chat/completions'
        : 'POST /v1/messages 或 POST /v1/chat/completions'
      : isGeminiImageModel(model)
        ? `POST /v1beta/models/${model.modelId}:generateContent`
      : `${model.endpoint.method} ${model.endpoint.path}`

  return (
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
      <QuickFact label="Endpoint" value={endpointValue} />
      <QuickFact label="Model ID" value={model.modelId} mono />
      <QuickFact label="Content-Type" value={contentType} mono />
      <QuickFact label={locale === 'en' ? 'Protocol' : '接口类型'} value={protocolHint} />
      <QuickFact label="Base URL" value={baseUrlHint} />
    </div>
  )
}

function QuickFact({
  label,
  value,
  mono = false,
}: {
  label: string
  value: string
  mono?: boolean
}) {
  return (
    <div className="rounded-lg border border-white/5 bg-white/[0.02] px-4 py-3">
      <div className="text-[11px] uppercase tracking-wider text-ink-500">
        {label}
      </div>
      <div
        className={
          'mt-1 text-sm leading-relaxed text-ink-100' +
          (mono ? ' font-mono text-violet-200' : '')
        }
      >
        {value}
      </div>
    </div>
  )
}

function apiOriginForModel(model: ModelEntry): string {
  return model.category === 'image' || model.category === 'video'
    ? 'https://img.gpt88.cc'
    : 'https://api.gpt88.cc'
}

function localizedCategoryTitle(category: ModelEntry['category'], locale: 'zh' | 'en') {
  if (locale === 'en') {
    switch (category) {
      case 'chat':
        return 'Chat'
      case 'image':
        return 'Image'
      case 'video':
        return 'Video'
      case 'audio':
        return 'Audio'
      default:
        return 'Model'
    }
  }

  return CATEGORY_META[category].title
}

function buildModelSeoDescription(model: ModelEntry, locale: 'zh' | 'en') {
  const category = localizedCategoryTitle(model.category, locale)
  const overview = model.overview[0] ?? model.tagline
  const trimmedOverview =
    overview.length > 140 ? `${overview.slice(0, 137)}...` : overview

  if (locale === 'en') {
    return `${model.provider} ${model.name} ${category} model. Model ID: ${model.modelId}. ${trimmedOverview}`
  }

  return `${model.provider} ${model.name} · ${category} 模型。Model ID: ${model.modelId}。${trimmedOverview}`
}

function apiReferencePathForModel(model: ModelEntry): string {
  switch (model.category) {
    case 'image':
      return '/docs/api/images'
    case 'chat':
      return '/docs/api/chat-completions'
    case 'video':
    case 'audio':
    default:
      return '/models'
  }
}

function apiReferenceLabelForModel(model: ModelEntry, locale: 'zh' | 'en'): string {
  switch (model.category) {
    case 'image':
      return locale === 'en' ? 'Images API' : '图片生成 API'
    case 'video':
      return locale === 'en' ? 'Video API reference on this page' : '当前模型页的 Video API 文档'
    case 'audio':
      return locale === 'en' ? 'Audio API reference on this page' : '当前模型页的 Audio API 文档'
    case 'chat':
    default:
      return 'Chat Completions API'
  }
}

function protocolHintForModel(model: ModelEntry, locale: 'zh' | 'en'): string {
  switch (model.category) {
    case 'image':
      if (isGeminiImageModel(model)) {
        return locale === 'en'
          ? 'Gemini-native image generation. generateContent returns images in inlineData base64.'
          : 'Gemini 原生图片生成接口，generateContent 返回 inlineData base64 图片'
      }
      return locale === 'en'
        ? 'Image generation endpoint. Supports text-to-image; some models also support image-to-image.'
        : '图像生成接口，支持文生图；部分模型支持图生图'
    case 'video':
      return locale === 'en' ? 'Video generation endpoint, usually async.' : '视频生成接口，通常为异步任务'
    case 'audio':
      return locale === 'en' ? 'Audio transcription endpoint with file upload.' : '音频转写接口，使用文件上传'
    case 'chat':
    default:
      return isAnthropicModel(model)
        ? locale === 'en'
          ? 'Claude family model. Claude-native tools should prefer the Anthropic Messages protocol; OpenAI-compatible tools can use the compatibility path.'
          : 'Claude 模型：Claude 工具优先用 Anthropic Messages 协议；OpenAI 工具可用兼容协议'
        : locale === 'en'
          ? 'OpenAI-compatible chat completions endpoint with streaming and non-streaming output.'
          : 'OpenAI 兼容对话补全接口，支持非流式和流式输出'
  }
}

function isAnthropicModel(model: ModelEntry): boolean {
  return model.provider.includes('Anthropic') || model.modelId.toLowerCase().startsWith('claude-')
}

function isOpenAIModel(model: ModelEntry): boolean {
  return model.provider.includes('OpenAI') || model.modelId.toLowerCase().startsWith('gpt-')
}

function isGeminiImageModel(model: ModelEntry): boolean {
  const id = model.modelId.toLowerCase()
  return id === 'nanobanana2' || id === 'gemini-3-pro-image-preview' || id === 'gemini-3.1-flash-image' || id === 'gemini-3-pro-image'
}

function chatBaseUrlHint(model: ModelEntry, locale: 'zh' | 'en'): string {
  if (isAnthropicModel(model)) {
    return locale === 'en'
      ? 'Use https://api.gpt88.cc for Claude Code / Anthropic SDK, OpenAI SDK, Cursor, and cURL.'
      : 'Claude Code / Anthropic SDK、OpenAI SDK、Cursor、cURL 统一使用 https://api.gpt88.cc。'
  }
  if (isOpenAIModel(model)) {
    return locale === 'en'
      ? 'Use https://api.gpt88.cc for OpenAI SDK, Cursor, and cURL.'
      : 'OpenAI SDK / Cursor / cURL 用 https://api.gpt88.cc。'
  }
  return locale === 'en'
    ? 'Use https://api.gpt88.cc for OpenAI-compatible and Claude-style tools.'
    : 'OpenAI 兼容工具和 Claude 风格工具统一使用 https://api.gpt88.cc。'
}

function ChatProtocolGuide({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  const anthropic = isAnthropicModel(model)
  return (
    <div className="rounded-lg border border-white/5 bg-white/[0.02] p-4">
      <h3 className="text-sm font-semibold text-ink-100">{locale === 'en' ? 'Chat Protocol Differences' : 'Chat 协议差异'}</h3>
      <p className="mt-1 text-sm leading-relaxed text-ink-300">
        {locale === 'en'
          ? 'For chat models, the protocol used by the client matters as much as the model name. Claude Code / Anthropic SDK and OpenAI SDK build different request paths.'
          : 'Chat 模型不只看模型名，还要看你使用的客户端协议。Claude Code / Anthropic SDK 和 OpenAI SDK 拼出来的路径不同。'}
      </p>
      <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
        <ProtocolCard
          title={locale === 'en' ? 'OpenAI Compatible' : 'OpenAI 兼容'}
          endpoint="POST /v1/chat/completions"
          baseUrl="https://api.gpt88.cc"
          body={`{ "model": "${model.modelId}", "messages": [...] }`}
          recommended={!anthropic}
        />
        <ProtocolCard
          title="Anthropic / Claude"
          endpoint="POST /v1/messages"
          baseUrl="https://api.gpt88.cc"
          body={`{ "model": "${model.modelId}", "messages": [...] }`}
          recommended={anthropic}
        />
      </div>
      <p className="mt-3 text-xs leading-relaxed text-ink-400">
        {anthropic
          ? locale === 'en'
            ? 'This model is in the Claude family. Claude Code, Anthropic SDK, OpenClaw, and similar tools should prefer the Anthropic / Claude path.'
            : '这个模型属于 Claude 系列；Claude Code、Anthropic SDK、OpenClaw 等工具建议优先走 Anthropic / Claude 风格。'
          : locale === 'en'
            ? 'This model is usually best accessed through the OpenAI-compatible protocol. Only use the Anthropic-style path when the target tool explicitly requires it.'
            : '这个模型更适合优先走 OpenAI 兼容协议；只有当目标工具明确支持 Claude 风格接入时，才使用 Anthropic 路径。'}
      </p>
    </div>
  )
}

function ProtocolCard({
  title,
  endpoint,
  baseUrl,
  body,
  recommended = false,
}: {
  title: string
  endpoint: string
  baseUrl: string
  body: string
  recommended?: boolean
}) {
  const { locale } = useLocale()
  return (
    <div className="rounded-lg border border-white/5 bg-ink-900/40 p-3">
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-xs font-semibold text-ink-100">{title}</span>
        {recommended ? (
          <span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-2 py-0.5 text-[10px] font-medium text-emerald-200">
            {locale === 'en' ? 'Recommended' : '推荐'}
          </span>
        ) : null}
      </div>
      <dl className="mt-3 space-y-2 text-xs leading-relaxed">
        <div>
          <dt className="text-ink-500">Base URL</dt>
          <dd className="font-mono text-violet-200">{baseUrl}</dd>
        </div>
        <div>
          <dt className="text-ink-500">Endpoint</dt>
          <dd className="font-mono text-ink-200">{endpoint}</dd>
        </div>
        <div>
          <dt className="text-ink-500">Body</dt>
          <dd className="font-mono text-ink-200">{body}</dd>
        </div>
      </dl>
    </div>
  )
}

function requestFieldsForModel(model: ModelEntry, locale: 'zh' | 'en'): FieldRow[] {
  switch (model.category) {
    case 'image':
      if (isGeminiImageModel(model)) {
        return geminiImageRequestFields(model, locale)
      }
      return [
        modelField(model, locale),
        {
          name: 'prompt',
          type: 'string',
          required: true,
          description: locale === 'en'
            ? <>Text instruction for image generation or editing. Describe the subject, style, composition, and anything that must remain unchanged.</>
            : <>生成或编辑图片的文字指令。建议写清主体、风格、构图和不希望改变的内容。</>,
        },
        {
          name: 'image',
          type: 'file | file[]',
          description: locale === 'en'
            ? <>Reference image file for image-to-image. The OpenAI editing flow uses uploaded files instead of image URLs.</>
            : <>图生图参考图文件。OpenAI 官方编辑接口使用上传文件，而不是图片 URL。</>,
        },
        {
          name: 'size',
          type: 'string',
          default: usesRatioSizeCopy(model) ? '1:1' : '1024x1024',
          description: usesRatioSizeCopy(model)
            ? locale === 'en'
              ? <>Aspect ratio such as <code>1:1</code>, <code>16:9</code>, <code>9:16</code>, or <code>auto</code>. Do not send pixel sizes like <code>1024x1024</code> to this model.</>
              : <>画幅比例，例如 <code>1:1</code>、<code>16:9</code>、<code>9:16</code>、<code>auto</code>。该模型不要传 <code>1024x1024</code> 这类像素尺寸。</>
            : locale === 'en'
              ? <>Output size or aspect configuration. Supported values vary by model and should be confirmed in the console.</>
              : <>输出尺寸或画幅配置。不同图像模型支持范围不同，以控制台为准。</>,
        },
        {
          name: 'resolution',
          type: 'string',
          default: usesRatioSizeCopy(model) ? '1K' : undefined,
          description: locale === 'en'
            ? <>Output quality, for example <code>1K</code>. Higher resolutions depend on the model and account configuration.</>
            : <>输出清晰度，例如 <code>1K</code>。是否支持更高清晰度以控制台为准。</>,
        },
        {
          name: 'n',
          type: 'integer',
          default: '1',
          description: locale === 'en'
            ? <>Number of images to generate. For batch jobs, watch account concurrency and rate limits.</>
            : <>生成图片数量。批量生成时请关注账号限速与并发。</>,
        },
      ]
    case 'video':
      return [
        modelField(model, locale),
        {
          name: 'prompt',
          type: 'string',
          required: true,
          description: locale === 'en' ? <>Describe the scene, camera movement, subject, style, and pacing.</> : <>视频画面、镜头运动、主体、风格和节奏描述。</>,
        },
        {
          name: 'image_url',
          type: 'string',
          description: locale === 'en' ? <>Optional reference image for image-to-video or first-frame guidance. Support depends on the specific model.</> : <>可选参考图，用于图生视频或首帧约束；是否支持取决于具体模型。</>,
        },
        {
          name: 'duration',
          type: 'integer',
          default: '6',
          description: locale === 'en' ? <>Target video duration in seconds. Allowed values depend on the model and current console configuration.</> : <>目标视频时长，单位秒。可用范围以模型和控制台配置为准。</>,
        },
        {
          name: 'aspect_ratio',
          type: 'string',
          default: '16:9',
          description: locale === 'en' ? <>Aspect ratio such as <code>16:9</code>, <code>9:16</code>, or <code>1:1</code>.</> : <>画幅比例，例如 <code>16:9</code>、<code>9:16</code>、<code>1:1</code>。</>,
        },
      ]
    case 'audio':
      return [
        modelField(model, locale),
        {
          name: 'file',
          type: 'File',
          required: true,
          description: locale === 'en' ? <>Audio file to transcribe, uploaded with <code>multipart/form-data</code>.</> : <>要转写的音频文件，使用 <code>multipart/form-data</code> 上传。</>,
        },
        {
          name: 'language',
          type: 'string',
          description: locale === 'en' ? <>Optional language hint such as <code>zh</code> or <code>en</code>. If omitted, the model auto-detects.</> : <>音频语言提示，例如 <code>zh</code>、<code>en</code>。不传时由模型自动判断。</>,
        },
        {
          name: 'prompt',
          type: 'string',
          description: locale === 'en' ? <>Optional context prompt to help with names, domain terminology, or meeting topics.</> : <>可选上下文提示，用于专有名词、会议主题或人名纠偏。</>,
        },
        {
          name: 'response_format',
          type: 'string',
          default: 'json',
          description: locale === 'en' ? <>Response format such as <code>json</code>, <code>text</code>, or <code>verbose_json</code>.</> : <>返回格式，例如 <code>json</code>、<code>text</code>、<code>verbose_json</code>。</>,
        },
      ]
    case 'chat':
    default:
      return [
        modelField(model, locale),
        {
          name: 'messages',
          type: 'array<Message>',
          required: true,
          description: locale === 'en'
            ? <>Conversation history. Each message includes <code>role</code> and <code>content</code>.</>
            : <>多轮对话历史。每条消息包含 <code>role</code> 和 <code>content</code>。</>,
        },
        {
          name: 'stream',
          type: 'boolean',
          default: 'false',
          description: locale === 'en' ? <>Enable SSE streaming. Useful for chat interfaces and long responses.</> : <>是否使用 SSE 流式返回。适合聊天界面和长回答。</>,
        },
        {
          name: 'temperature',
          type: 'number',
          default: '1',
          description: locale === 'en' ? <>Sampling temperature. Higher values produce more variation; production workloads usually start with a fixed value.</> : <>采样温度，值越高越发散。正式业务建议先固定后再调优。</>,
        },
        {
          name: 'max_tokens',
          type: 'integer',
          description: locale === 'en' ? <>Maximum output tokens for this request. Real context limits should be confirmed in the console.</> : <>本次生成的最大 token 数。模型上下文边界以控制台为准。</>,
        },
        {
          name: 'response_format',
          type: 'object',
          description: locale === 'en' ? <>Structured output config, for example <code>{'{ "type": "json_object" }'}</code>.</> : <>结构化输出配置，例如 <code>{'{ "type": "json_object" }'}</code>。</>,
        },
        {
          name: 'tools',
          type: 'array<Tool>',
          description: locale === 'en' ? <>Function-calling tool definitions. Availability depends on the model and account configuration.</> : <>Function calling 工具定义。是否支持取决于具体模型和账号配置。</>,
        },
      ]
  }
}

function headerFieldsForModel(model: ModelEntry, locale: 'zh' | 'en'): FieldRow[] {
  const contentType =
    model.category === 'audio' ? 'multipart/form-data' : 'application/json'
  const headers: FieldRow[] = [
    {
      name: 'Authorization',
      type: 'string',
      required: true,
      description: (
        locale === 'en'
          ? <>Send <code>Bearer {'<GPT88_API_KEY>'}</code>. Create the API key in the gpt88.cc console.</>
          : <>使用 <code>Bearer {'<GPT88_API_KEY>'}</code>。API Key 在 gpt88.cc 控制台创建。</>
      ),
    },
    {
      name: 'Content-Type',
      type: 'string',
      required: true,
      default: contentType,
      description: locale === 'en' ? <>Request body format. Audio transcription uploads use <code>multipart/form-data</code>.</> : <>请求体格式。音频转写上传文件时使用 <code>multipart/form-data</code>。</>,
    },
    {
      name: 'Accept',
      type: 'string',
      default: model.category === 'chat' ? 'application/json 或 text/event-stream' : 'application/json',
      description: locale === 'en' ? <>Non-streaming requests return JSON; streaming chat requests return SSE chunks.</> : <>非流式接口返回 JSON；Chat 流式请求会返回 SSE 数据流。</>,
    },
  ]
  if (isGeminiImageModel(model)) {
    headers.push({
      name: 'x-goog-api-key',
      type: 'string',
      description: locale === 'en' ? <>If the current route does not accept <code>Authorization: Bearer</code>, pass the API key with this header instead.</> : <>如果当前中转线路不接受 <code>Authorization: Bearer</code>，可改用该 Header 传 API Key。</>,
    })
  }
  return headers
}

function responseFieldsForModel(model: ModelEntry, locale: 'zh' | 'en'): FieldRow[] {
  switch (model.category) {
    case 'image':
      if (isGeminiImageModel(model)) {
        return [
          { name: 'candidates', type: 'array<Candidate>', required: true, description: locale === 'en' ? <>Gemini candidate array.</> : <>Gemini 返回候选结果数组。</> },
          {
            name: 'candidates[].content.parts',
            type: 'array<Part>',
            required: true,
            description: locale === 'en' ? <>Contains text and image parts. Image bytes are usually in <code>inlineData.data</code>.</> : <>包含文本 part 和图片 part。图片通常在 <code>inlineData.data</code> 中。</>,
          },
          {
            name: 'inlineData.data',
            type: 'string',
            description: locale === 'en' ? <>Base64 image payload. Decode it and write it to a PNG file.</> : <>base64 编码图片数据，提取后可写入 PNG 文件。</>,
          },
          {
            name: 'usageMetadata',
            type: 'object',
            description: locale === 'en' ? <>Gemini-style usage metadata. Whether it is returned depends on the actual response.</> : <>Gemini 风格用量信息；是否返回以实际响应为准。</>,
          },
        ]
      }
      return [
        { name: 'created', type: 'integer', required: true, description: locale === 'en' ? <>Creation time as Unix seconds.</> : <>生成时间，Unix 秒。</> },
        {
          name: 'data',
          type: 'array<Image>',
          required: true,
          description: locale === 'en' ? <>Generated image array, usually containing <code>url</code> or <code>b64_json</code>.</> : <>生成结果数组，通常包含图片 <code>url</code> 或 <code>b64_json</code>。</>,
        },
        {
          name: 'usage',
          type: 'object',
          description: locale === 'en' ? <>Some models return usage data. Actual presence depends on the model response.</> : <>部分模型会返回用量统计；是否返回以模型实际响应为准。</>,
        },
      ]
    case 'video':
      return [
        { name: 'id', type: 'string', required: true, description: locale === 'en' ? <>Video task ID for later status polling.</> : <>视频生成任务 ID，用于后续查询任务状态。</> },
        { name: 'status', type: 'string', required: true, description: locale === 'en' ? <>Task status such as <code>queued</code>, <code>processing</code>, or <code>succeeded</code>.</> : <>任务状态，例如 <code>queued</code>、<code>processing</code>、<code>succeeded</code>。</> },
        { name: 'model', type: 'string', required: true, description: locale === 'en' ? <>Model ID used for this request.</> : <>本次使用的模型 ID。</> },
        { name: 'url', type: 'string', description: locale === 'en' ? <>Video file URL after completion. It may be empty while the async task is still running.</> : <>任务完成后的视频文件 URL；异步任务未完成时可能为空。</> },
      ]
    case 'audio':
      return [
        { name: 'text', type: 'string', required: true, description: locale === 'en' ? <>Full transcription text.</> : <>完整转写文本。</> },
        { name: 'language', type: 'string', description: locale === 'en' ? <>Detected or explicitly requested language.</> : <>识别到或指定的语言。</> },
        { name: 'duration', type: 'number', description: locale === 'en' ? <>Audio duration in seconds. Returned fields depend on the response format.</> : <>音频时长，单位秒。是否返回取决于响应格式。</> },
        { name: 'segments', type: 'array<Segment>', description: locale === 'en' ? <>Segment timeline data, usually returned only in detailed formats such as <code>verbose_json</code>.</> : <>分段时间轴，仅在 verbose_json 等详细格式中返回。</> },
      ]
    case 'chat':
    default:
      return [
        { name: 'id', type: 'string', required: true, description: locale === 'en' ? <>Unique completion ID for tracing and debugging.</> : <>本次补全的唯一 ID，便于排障关联日志。</> },
        { name: 'object', type: 'string', required: true, description: locale === 'en' ? <>Usually <code>chat.completion</code> or a streaming chunk type.</> : <>固定为 <code>chat.completion</code> 或流式 chunk 类型。</> },
        { name: 'model', type: 'string', required: true, description: locale === 'en' ? <>Actual model ID that handled inference.</> : <>实际承担推理的模型 ID。</> },
        {
          name: 'choices',
          type: 'array<Choice>',
          required: true,
          description: locale === 'en' ? <>Generated choices including <code>message</code>, <code>delta</code>, and <code>finish_reason</code>.</> : <>生成结果数组，包含 <code>message</code>、<code>delta</code> 或 <code>finish_reason</code>。</>,
        },
        {
          name: 'usage',
          type: 'object',
          description: locale === 'en' ? <>Token usage statistics. Streaming calls may return this only at the end or in non-streaming mode.</> : <>Token 用量统计。流式请求可能在结束包或非流式响应中返回。</>,
        },
      ]
  }
}

function statusCodeRows(model: ModelEntry, locale: 'zh' | 'en'): FieldRow[] {
  return [
    {
      name: '200',
      type: 'OK',
      required: true,
      description: model.category === 'video'
        ? locale === 'en'
          ? <>Request accepted or task created successfully. The response includes a task ID and task status.</>
          : <>请求已被接受或任务创建成功，响应中包含任务状态和任务 ID。</>
        : locale === 'en'
          ? <>Request succeeded. See the response field table above for the response body shape.</>
          : <>请求成功，响应体结构见上方响应字段。</>,
    },
    {
      name: '400',
      type: 'Bad Request',
      description: locale === 'en' ? <>Invalid request fields, such as missing required fields, unsupported image size format, or unsupported file type.</> : <>请求字段不合法，例如缺少必填字段、图片尺寸格式错误或文件格式不支持。</>,
    },
    {
      name: '401',
      type: 'Unauthorized',
      description: locale === 'en' ? <>API key is missing, invalid, or malformed.</> : <>API Key 缺失、无效或格式错误。</>,
    },
    {
      name: '404',
      type: 'Not Found',
      description: (
        <>
          {locale === 'en'
            ? <>Endpoint or model not found. Confirm the path is <code>{model.endpoint.path}</code> and the model ID is <code>{model.modelId}</code>.</>
            : <>Endpoint 或模型不存在。请确认路径为 <code>{model.endpoint.path}</code>，模型 ID 为 <code>{model.modelId}</code>。</>}
        </>
      ),
    },
    {
      name: '429',
      type: 'Rate Limited',
      description: locale === 'en' ? <>Rate limit, concurrency cap, or insufficient balance. Check the console for the current allowance.</> : <>触发限速、并发限制或余额不足。控制台会展示当前账号可用额度。</>,
    },
    {
      name: '5xx',
      type: 'Upstream Error',
      description: locale === 'en' ? <>Upstream or request failure. Retry with the same Base URL and keep the request ID for debugging.</> : <>上游或请求异常。保持统一 Base URL 重试，并保留请求 ID 便于排查。</>,
    },
  ]
}

function geminiImageRequestFields(model: ModelEntry, locale: 'zh' | 'en'): FieldRow[] {
  return [
    {
      name: 'contents',
      type: 'array<Content>',
      required: true,
      description: locale === 'en' ? <>Gemini <code>generateContent</code> input. Put the text prompt in <code>contents[].parts[].text</code>.</> : <>Gemini generateContent 输入。文字提示放在 <code>contents[].parts[].text</code>。</>,
    },
    {
      name: 'contents[].parts[].text',
      type: 'string',
      required: true,
      description: locale === 'en' ? <>Image-generation prompt covering subject, style, aspect ratio, details, and constraints.</> : <>图片生成提示词，例如主体、风格、比例、细节和限制。</>,
    },
    {
      name: 'contents[].parts[].fileData',
      type: 'object',
      description: locale === 'en' ? <>Reference image for image-to-image. Include <code>mimeType</code> and <code>fileUri</code>. The referenced file must be reachable by the server.</> : <>图生图参考图。包含 <code>mimeType</code> 与 <code>fileUri</code>，图片 URL 需要能被服务端访问。</>,
    },
    {
      name: 'generationConfig.responseModalities',
      type: 'string[]',
      required: true,
      default: '["TEXT", "IMAGE"]',
      description: locale === 'en' ? <>Request both text and image outputs. Include <code>IMAGE</code> when generating images.</> : <>要求模型同时返回文本与图片。生成图片时需要包含 <code>IMAGE</code>。</>,
    },
    {
      name: 'generationConfig.responseFormat.image.aspectRatio',
      type: 'string',
      default: '1:1',
      description: locale === 'en' ? <>Aspect ratio such as <code>1:1</code>, <code>16:9</code>, <code>9:16</code>, <code>4:3</code>, or <code>3:4</code>.</> : <>图片比例，例如 <code>1:1</code>、<code>16:9</code>、<code>9:16</code>、<code>4:3</code>、<code>3:4</code>。</>,
    },
    {
      name: 'generationConfig.responseFormat.image.imageSize',
      type: 'string',
      default: '1K',
      description: locale === 'en' ? <>Output size. Use uppercase values such as <code>1K</code>, <code>2K</code>, or <code>4K</code>.</> : <>输出清晰度，使用大写，例如 <code>1K</code>、<code>2K</code>、<code>4K</code>。</>,
    },
    {
      name: 'model',
      type: 'path parameter',
      required: true,
      description: (
        <>
          {locale === 'en'
            ? <>The model ID is part of the path: <code>/v1beta/models/{model.modelId}:generateContent</code>.</>
            : <>当前模型 ID 写在路径里：<code>/v1beta/models/{model.modelId}:generateContent</code>。</>}
        </>
      ),
    },
  ]
}

function modelField(model: ModelEntry, locale: 'zh' | 'en'): FieldRow {
  return {
    name: 'model',
    type: 'string',
    required: true,
    description: (
      locale === 'en'
        ? <>Current model ID: <code>{model.modelId}</code>. Preserve the exact casing when copying.</>
        : <>当前模型 ID：<code>{model.modelId}</code>。复制时请保持大小写一致。</>
    ),
  }
}

function usesRatioSizeCopy(model: ModelEntry): boolean {
  const id = model.modelId.toLowerCase()
  return id === 'nanobanana2' || id === 'gemini-3-pro-image-preview'
}

function ErrorChecklist({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  return (
    <div className="rounded-lg border border-white/5 bg-white/[0.02] p-4">
      <h3 className="text-sm font-semibold text-ink-100">{locale === 'en' ? 'Errors and Troubleshooting' : '错误与排查'}</h3>
      <ul className="mt-3 space-y-2 text-sm leading-relaxed text-ink-300">
        <li>
          {locale === 'en'
            ? <><code>401</code>: verify <code>Authorization</code> is <code>Bearer {'<API_KEY>'}</code> and the key is still valid.</>
            : <><code>401</code>：检查 <code>Authorization</code> 是否为<code> Bearer {'<API_KEY>'}</code>，以及 Key 是否仍有效。</>}
        </li>
        <li>
          {locale === 'en'
            ? <><code>404</code>: confirm the endpoint is <code>{model.endpoint.path}</code> and the model ID <code>{model.modelId}</code> is available in the console.</>
            : <><code>404</code>：检查 endpoint 是否为 <code>{model.endpoint.path}</code>，以及模型名 <code>{model.modelId}</code> 是否在控制台可见。</>}
        </li>
        <li>
          {locale === 'en'
            ? <><code>429</code>: reduce concurrency, shorten requests, or check balance and quota in the console.</>
            : <><code>429</code>：触发限速或余额不足时，降低并发、缩短请求，或到控制台查看额度。</>}
        </li>
        <li>
          {locale === 'en'
            ? <><code>5xx</code>: retry with the same Base URL and keep the request ID for debugging.</>
            : <><code>5xx</code>：保持统一 Base URL 重试，并记录请求 ID 方便排障。</>}
        </li>
      </ul>
    </div>
  )
}

function ModelRequestExamples({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  if (model.category !== 'image') {
    return <CodeTabs tabs={model.examples} />
  }

  const textToImageTabs = model.examples.filter(
    tab => tab.label.startsWith('文生图') || tab.label.toLowerCase().startsWith('text-to-image'),
  )
  const imageToImageTabs = model.examples.filter(
    tab => tab.label.startsWith('图生图') || tab.label.toLowerCase().startsWith('image-to-image'),
  )

  if (textToImageTabs.length === 0 || imageToImageTabs.length === 0) {
    return <CodeTabs tabs={model.examples} />
  }

  return (
    <div className="space-y-6">
      <ExampleGroup
        title={locale === 'en' ? 'Text-to-Image' : '文生图'}
        description={locale === 'en' ? 'Send only a prompt and let the model generate a new image from scratch.' : '只传 prompt，由模型直接生成一张新图片。'}
        tabs={localizeExampleTabs(textToImageTabs, locale)}
      />
      <ExampleGroup
        title={locale === 'en' ? 'Image-to-Image' : '图生图'}
        description={locale === 'en' ? 'Upload reference image files and continue generation while preserving subject matter or style.' : '上传参考图文件，在保留主体或风格的基础上继续生成。'}
        tabs={localizeExampleTabs(imageToImageTabs, locale)}
        highlighted
      />
    </div>
  )
}

function ExampleGroup({
  title,
  description,
  tabs,
  highlighted = false,
}: {
  title: string
  description: string
  tabs: CodeTab[]
  highlighted?: boolean
}) {
  const { locale } = useLocale()
  return (
    <div className="rounded-xl border border-white/5 bg-white/[0.02] p-4">
      <div className="flex flex-wrap items-center gap-2">
        <h3 className="text-sm font-semibold text-ink-100">{title}</h3>
        {highlighted ? (
          <span className="rounded-full border border-cyan-400/25 bg-cyan-400/10 px-2 py-0.5 text-[11px] font-medium text-cyan-200">
            {locale === 'en' ? 'Reference image flow' : '参考图生成'}
          </span>
        ) : null}
      </div>
      <p className="mt-1 text-xs leading-relaxed text-ink-400">{description}</p>
      <CodeTabs tabs={tabs} className="mb-0 mt-3" />
    </div>
  )
}

/* ──────────────────────────────────────────────────────────────────
 * 期望响应：每个分类各自有一个示例 JSON，让读者看完调用就知道返回什么
 * ────────────────────────────────────────────────────────────────── */
function ExpectedResponse({ model }: { model: ModelEntry }) {
  const { locale } = useLocale()
  const code = useMemo(() => buildExpectedResponse(model, locale), [locale, model])
  return (
    <div className="mt-4">
      <p className="text-sm text-ink-300">{locale === 'en' ? 'Expected response (trimmed example):' : '期望响应（精简示例）：'}</p>
      <CodeBlock lang="json" filename="200 OK" code={code} className="mt-2" />
    </div>
  )
}

function buildExpectedResponse(model: ModelEntry, locale: 'zh' | 'en'): string {
  switch (model.category) {
    case 'chat':
      return `{
  "id": "chatcmpl-${model.slug.slice(0, 8)}",
  "object": "chat.completion",
  "created": 1730000000,
  "model": "${model.modelId}",
  "choices": [
    {
      "index": 0,
      "finish_reason": "stop",
      "message": { "role": "assistant", "content": "..." }
    }
  ],
  "usage": { "prompt_tokens": 24, "completion_tokens": 64, "total_tokens": 88 }
}`
    case 'image':
      if (isGeminiImageModel(model)) {
        return `{
  "candidates": [
    {
      "content": {
        "parts": [
          { "text": "${locale === 'en' ? 'Image generated.' : '已生成图片。'}" },
          {
            "inlineData": {
              "mimeType": "image/png",
              "data": "iVBORw0KGgoAAA..."
            }
          }
        ]
      }
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 24,
    "totalTokenCount": 88
  }
}`
      }
      return `{
  "created": 1730000000,
  "data": [
    { "url": "https://cdn.gpt88.cc/images/${model.slug}-001.png" }
  ]
}`
    case 'video':
      return `{
  "id": "video_${model.slug.slice(0, 8)}",
  "status": "queued",
  "model": "${model.modelId}",
  "created": 1730000000
}`
    case 'audio':
      // TTS 与 STT 返回不同；用 model.endpoint.path 区分
      if (model.endpoint.path.includes('transcriptions')) {
        return `{
  "text": "${locale === 'en' ? 'Full transcription text...' : '完整识别文本……'}",
  "language": "zh",
  "duration": 124.6,
  "segments": [
    { "id": 0, "start": 0.0, "end": 4.2, "text": "..." }
  ]
}`
      }
      return locale === 'en'
        ? `// Binary response: Content-Type: audio/mpeg
// Write it directly to disk, for example speech.mp3`
        : `// 二进制响应：Content-Type: audio/mpeg
// 直接写入磁盘即可，例如 speech.mp3`
  }
}

function localizeExampleTabs(tabs: CodeTab[], locale: 'zh' | 'en'): CodeTab[] {
  if (locale !== 'en') return tabs

  return tabs.map(tab => ({
    ...tab,
    label: tab.label
      .replace(/^文生图/, 'Text-to-Image')
      .replace(/^图生图/, 'Image-to-Image'),
  }))
}

/* ──────────────────────────────────────────────────────────────────
 * 模型未找到分支
 *
 * 当用户访问 /models/<未知 slug> 时显示。
 *
 * 设计要点：
 * - 不再使用 <Navigate>。原因见文件顶部说明：纯客户端重定向在静态深链
 *   场景下要么闪一下、要么和 SPA fallback 缺失叠加成 404。
 * - 这里给出明确中文文案、原始 slug 回显，以及"返回模型导航"和
 *   "查看快速开始"两条出口，让用户立刻有下一步操作。
 * - 复用现有 Tailwind class 与 lucide 图标，不引入新依赖。
 * ────────────────────────────────────────────────────────────────── */
function ModelNotFound({ slug }: { slug?: string }) {
  const { locale } = useLocale()
  const t =
    locale === 'en'
      ? {
          title: 'Model not found',
          body: 'No entry in the current catalog matched',
          tail: '. The model may have been removed, renamed, or is not available yet.',
          all: 'View all models',
          quickstart: 'Open Quickstart',
        }
      : {
          title: '没有找到这个模型',
          body: '我们在模型清单里没有匹配',
          tail: '的条目。可能是模型已下线、链接拼写有误，或者还未上线。',
          all: '查看全部模型',
          quickstart: '先看快速开始',
        }
  return (
    <section className="mx-auto max-w-2xl px-4 py-24 text-center sm:px-6 lg:px-8">
      <div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-violet-500/10 text-violet-300 ring-1 ring-violet-500/30">
        <SearchX className="h-6 w-6" />
      </div>
      <h1 className="mt-6 text-2xl font-semibold tracking-tight text-ink-50 sm:text-3xl">
        {t.title}
      </h1>
      <p className="mt-3 text-sm text-ink-300 sm:text-base">
        {t.body}{' '}
        {slug ? (
          <>
            <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-violet-200">
              {slug}
            </code>
          </>
        ) : null}
        {t.tail}
      </p>

      <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
        {/* 站内深链统一使用 <Link>，避免在 BrowserRouter 下整页刷新 */}
        <Link
          to={localizePath('/models/', locale)}
          className="inline-flex items-center gap-2 rounded-md bg-violet-500 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-400"
        >
          <Compass className="h-4 w-4" />
          {t.all}
        </Link>
        <Link
          to={localizePath('/docs/quickstart/', locale)}
          className="inline-flex items-center gap-2 rounded-md border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold text-ink-100 hover:border-violet-500/40 hover:bg-violet-500/10"
        >
          {t.quickstart}
        </Link>
      </div>
    </section>
  )
}
